In [2]:
import pandas as pd

pd.read_csv("binding_np_classifier.csv").sort_values(by="mcc validation set", ascending=False)

,Model type,Trial,F1_macro_validation_set,Precision validation set,recall validation set,roc_auc validation set,accuracy validation set,mcc validation set,Batch size,Learning rate,Protein layers,Compound layers,Final head layers,Epochs,batch_norm,dropout,best epoch
12,gat,12,0.783983,0.778762,0.789522,0.935487,0.883939,0.704786,32,0.000050,"[2560, 1280, 1280, 640]","[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280]",51,True,0.433603,19
39,gat,39,0.783915,0.769255,0.799482,0.936420,0.882378,0.703559,32,0.000063,"[2560, 1280, 1280]","[2560, 1280]","[2560, 1280]",97,True,0.392985,15
46,gat,46,0.782133,0.777688,0.787378,0.936446,0.883015,0.702541,32,0.000061,"[2560, 1280]","[2560, 1280]","[2560, 1280]",137,True,0.272896,11
48,gat,48,0.781690,0.771458,0.792472,0.936475,0.882007,0.701113,32,0.000058,"[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280, 640]","[2560, 1280, 1280, 1280]",154,True,0.293368,15
49,gat,49,0.781238,0.769690,0.794020,0.935425,0.881623,0.700686,64,0.000059,"[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280, 640]","[2560, 1280, 1280, 1280]",152,True,0.273401,12
44,gat,44,0.779573,0.775209,0.784903,0.934437,0.881294,0.698798,32,0.000062,"[2560, 2560, 2560, 1280]","[2560, 1280]","[2560, 1280, 1280, 1280, 1280]",137,True,0.355175,24
14,gat,14,0.780094,0.759346,0.802322,0.935440,0.879383,0.697729,32,0.000050,"[2560, 1280, 1280, 1280, 640]","[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280]",50,True,0.484933,17
41,gat,41,0.778589,0.772122,0.785813,0.934320,0.880969,0.697554,32,0.000065,"[2560, 2560, 2560, 1280]","[2560, 1280]","[2560, 1280]",95,True,0.347118,12
31,gat,31,0.779386,0.763212,0.796821,0.935612,0.879795,0.697395,32,0.000091,"[2560, 1280, 1280, 640]","[2560, 1280, 1280, 640]","[2560, 1280]",60,True,0.427762,20
32,gat,32,0.773555,0.783181,0.765512,0.933798,0.880912,0.693488,32,0.000088,"[2560, 1280]","[2560, 1280]","[2560, 1280]",73,True,0.334395,17
35,gat,35,0.775413,0.772412,0.778643,0.933174,0.879680,0.693349,16,0.000070,"[2560, 1280]","[2560, 1280, 1280, 640]","[2560, 1280]",54,True,0.303489,23
45,gat,45,0.775409,0.764099,0.787609,0.933918,0.878415,0.692478,32,0.000064,"[2560, 2560, 2560, 1280]","[2560, 1280]","[2560, 1280]",138,True,0.356321,12
11,gat,11,0.770849,0.770264,0.771799,0.932956,0.877767,0.687668,32,0.000055,"[2560, 1280, 1280, 640]","[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280]",77,True,0.351863,16
27,gat,27,0.771176,0.767440,0.775137,0.933639,0.877396,0.687544,32,0.000098,"[2560, 1280]","[2560, 1280, 1280, 640]","[2560, 1280]",59,True,0.430165,17
22,gat,22,0.766195,0.781644,0.752159,0.928759,0.877929,0.684248,32,0.000077,"[2560, 1280, 1280, 1280, 1280]","[2560, 1280, 1280, 1280, 640]",[1280],62,True,0.247091,13
42,gat,42,0.767786,0.764787,0.771387,0.931226,0.875891,0.683378,32,0.000062,"[2560, 2560, 2560, 1280]","[2560, 1280]","[2560, 1280]",97,True,0.423154,8
13,gat,13,0.764885,0.775373,0.756532,0.929877,0.876162,0.681811,32,0.000061,"[2560, 1280, 1280, 640]","[2560, 1280]","[2560, 2560, 2560, 1280]",52,True,0.481240,13
43,gat,43,0.765779,0.769746,0.762735,0.929991,0.875901,0.681787,32,0.000050,"[2560, 1280]","[2560, 1280]","[2560, 1280]",129,True,0.489885,11
29,gat,29,0.768058,0.753041,0.784040,0.929701,0.873725,0.681779,16,0.000065,"[2560, 1280, 1280, 1280, 640]","[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280]",89,True,0.428987,36
25,gat,25,0.764057,0.768100,0.760668,0.928658,0.874746,0.679101,32,0.000053,"[2560, 1280, 1280, 640]","[2560, 2560, 2560, 1280]","[2560, 1280, 1280, 1280, 1280]",92,True,0.557883,21
16,gat,16,0.761529,0.770294,0.754225,0.928520,0.874306,0.676868,32,0.000108,"[2560, 1280, 640]","[1280, 640]","[2560, 640]",75,True,0.643612,17
34,gat,34,0.759868,0.764943,0.755266,0.927543,0.872828,0.673597,32,0.000119,"[2560, 1280]","[2560, 1280, 1280, 640]","[2560, 1280]",71,True,0.423420,11
47,gat,47,0.755021,0.788972,0.725364,0.930927,0.874494,0.672606,16,0.000077,"[2560, 1280]","[2560, 1280]","[2560, 1280, 1280, 1280, 1280]",137,False,0.192259,15
36,gat,36,0.749152,0.784519,0.718018,0.927737,0.872092,0.665271,32,0.000089,"[2560, 1280]","[2560, 1280]","[2560, 1280]",68,False,0.528256,13
21,gat,21,0.752089,0.766434,0.739122,0.925491,0.870406,0.665004,32,0.000050,"[2560, 1280]","[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280]",65,True,0.374032,17
19,gat,19,0.748108,0.768405,0.731680,0.923203,0.869276,0.661560,32,0.000086,"[2560, 1280]","[2560, 1280]","[2560, 1280]",104,True,0.572795,12
23,gat,23,0.746740,0.764170,0.733546,0.924767,0.867846,0.659222,32,0.000069,"[2560, 1280]","[2560, 1280, 1280]","[2560, 1280]",81,True,0.395936,8
10,gat,10,0.740323,0.773074,0.713367,0.922314,0.867410,0.653859,32,0.000080,"[2560, 1280, 1280, 640]","[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280]",80,True,0.370363,6
26,gat,26,0.741417,0.738896,0.745297,0.919569,0.861605,0.647562,32,0.000152,"[2560, 1280]","[2560, 1280]","[2560, 1280]",70,True,0.289184,14
33,gat,33,0.738070,0.753631,0.723964,0.918670,0.863341,0.646307,32,0.000086,"[1280, 640]","[2560, 1280]","[2560, 1280]",60,True,0.320798,12
24,gat,24,0.731297,0.752135,0.714275,0.916808,0.860971,0.639232,32,0.000102,[2560],"[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280]",51,True,0.455909,26
15,gat,15,0.732176,0.751885,0.713699,0.917018,0.860628,0.638565,32,0.000117,"[2560, 1280, 1280, 1280, 640]","[2560, 1280, 1280, 1280, 1280]","[1280, 640]",50,True,0.515135,17
20,gat,20,0.706001,0.763064,0.662713,0.903343,0.854987,0.615875,32,0.000139,"[2560, 1280]",[640],[640],89,True,0.694675,12
28,gat,28,0.697864,0.758871,0.647729,0.903414,0.850675,0.603680,32,0.000071,"[2560, 1280]",[2560],"[2560, 1280]",112,True,0.181753,5
17,gat,17,0.686386,0.753723,0.634063,0.895693,0.847672,0.592570,32,0.000158,"[2560, 1280, 1280, 1280, 640]",[1280],"[2560, 1280, 640]",100,True,0.477942,14
4,gat,4,0.671246,0.770770,0.596428,0.898159,0.844940,0.580949,16,0.000505,"[2560, 1280, 1280, 640]","[2560, 1280, 1280, 1280]",[2560],106,False,0.236462,17
30,gat,30,0.672048,0.721375,0.635323,0.886311,0.838322,0.570374,64,0.000166,"[2560, 1280]","[2560, 1280]","[2560, 1280]",118,True,0.516091,5
40,gat,40,0.663927,0.750473,0.602608,0.893395,0.839795,0.570069,64,0.000324,"[2560, 1280, 1280]","[2560, 640]","[2560, 1280]",163,False,0.391712,15
5,gat,5,0.664908,0.749389,0.598566,0.889323,0.839200,0.567485,32,0.000344,"[2560, 640]","[2560, 1280]",[2560],193,False,0.587494,5
8,gat,8,0.649607,0.748055,0.575176,0.885663,0.834716,0.552440,64,0.000250,[640],"[2560, 1280]",[2560],147,False,0.040616,9
38,gat,38,0.620524,0.812831,0.505122,0.889359,0.836203,0.549136,16,0.000117,"[2560, 1280]","[2560, 1280]","[2560, 2560, 2560, 1280, 640]",58,False,0.603831,9
37,gat,37,0.646789,0.737363,0.582953,0.882008,0.832040,0.548454,64,0.000200,"[2560, 1280]","[2560, 1280]","[2560, 1280, 1280]",82,True,0.457878,3
6,gat,6,0.579769,0.781864,0.463682,0.872437,0.822114,0.504019,64,0.000658,"[2560, 640]","[2560, 1280, 640]","[2560, 1280]",187,False,0.693985,14
0,gat,0,0.592354,0.723344,0.508661,0.863062,0.816983,0.495166,64,0.000547,"[2560, 1280]","[2560, 1280]","[2560, 1280, 1280]",141,True,0.826341,4
1,gat,1,0.491680,0.808537,0.369173,0.845485,0.805136,0.446652,64,0.001077,"[1280, 640]","[2560, 1280]","[2560, 1280, 1280]",149,False,0.321981,4
9,gat,9,0.296379,0.880658,0.179835,0.767425,0.774084,0.330360,16,0.000221,"[2560, 2560, 2560, 1280, 640]","[2560, 1280]","[2560, 1280, 1280, 1280]",128,False,0.779245,7
3,gat,3,0.224346,0.693485,0.133977,0.700935,0.763377,0.252762,16,0.001255,"[2560, 1280, 1280]","[2560, 2560, 2560, 1280, 640]","[2560, 2560, 2560, 1280, 640]",128,True,0.792299,18
2,gat,2,0.008546,0.226361,0.004380,0.505346,0.731051,0.000701,16,0.001070,"[2560, 2560, 2560, 1280]","[2560, 640]","[2560, 1280]",155,False,0.887857,1
7,gat,7,0.000000,0.000000,0.000000,0.540138,0.733183,0.000000,64,0.002665,"[2560, 1280, 1280, 1280]","[2560, 1280]","[2560, 1280, 1280, 1280, 640]",173,True,0.950252,3
18,gat,18,0.000000,0.000000,0.000000,0.496884,0.733183,0.000000,32,0.000050,[1280],"[2560, 1280]","[2560, 1280, 1280, 640]",64,True,0.992517,0

In [5]:
import pandas as pd

dataset = pd.read_csv("train_dataset_w_representation_filtered.csv")

In [7]:
train = dataset[dataset["kfold_0"] == "train"]
valid = dataset[dataset["kfold_0"] == "valid"]
print("train", train.Binding.value_counts())
print("valid", valid.Binding.value_counts())

train 0.0    30034
1.0    10925
Name: Binding, dtype: int64
valid 0.0    7476
1.0    2725
Name: Binding, dtype: int64

In [8]:
train = dataset[dataset["kfold_1"] == "train"]
valid = dataset[dataset["kfold_1"] == "valid"]
print("train", train.Binding.value_counts())
print("valid", valid.Binding.value_counts())

train 0.0    29940
1.0    10905
Name: Binding, dtype: int64
valid 0.0    7570
1.0    2745
Name: Binding, dtype: int64

In [9]:
train = dataset[dataset["kfold_2"] == "train"]
valid = dataset[dataset["kfold_2"] == "valid"]
print("train", train.Binding.value_counts())
print("valid", valid.Binding.value_counts())

train 0.0    29858
1.0    10877
Name: Binding, dtype: int64
valid 0.0    7652
1.0    2773
Name: Binding, dtype: int64

In [1]:
import pandas as pd 

pd.read_csv("binding_np_classifier.csv").sort_values(by="mcc validation set", ascending=False)

,Model type,Trial,F1_macro_validation_set,Precision validation set,recall validation set,roc_auc validation set,accuracy validation set,mcc validation set,Batch size,Learning rate,Protein layers,Compound layers,Final head layers,Epochs,batch_norm,dropout,best epoch
13,gat,15,0.808232,0.826004,0.791209,0.944799,0.899824,0.740793,32,0.000062,"[2560, 1280, 1280, 640]","[2560, 1280]","[2560, 2560, 2560, 1280]",85,True,0.466625,24
21,gat,23,0.810150,0.807496,0.812821,0.947802,0.898358,0.740760,32,0.000050,"[2560, 1280, 1280, 640]","[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280]",77,True,0.371755,20
28,gat,30,0.809705,0.800573,0.819048,0.948955,0.897283,0.739464,32,0.000051,"[2560, 1280]","[2560, 1280, 1280, 1280]","[2560, 1280]",105,True,0.263104,14
38,gat,40,0.799691,0.845934,0.758242,0.949887,0.898651,0.734091,16,0.000051,"[2560, 1280]","[2560, 1280]","[2560, 1280, 1280]",105,False,0.193145,18
10,gat,12,0.799632,0.802583,0.796703,0.947055,0.893471,0.727092,32,0.000080,"[2560, 1280, 1280, 640]","[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280]",80,True,0.370363,19
37,gat,39,0.800146,0.795224,0.805128,0.944136,0.892690,0.726829,64,0.000064,"[2560, 1280]","[2560, 1280]","[2560, 1280]",82,True,0.268667,11
11,gat,13,0.796398,0.799041,0.793773,0.943246,0.891712,0.722648,32,0.000055,"[2560, 1280, 1280, 640]","[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280]",77,True,0.351863,16
29,gat,31,0.796353,0.777855,0.815751,0.942749,0.888683,0.720206,16,0.000053,"[2560, 1280, 1280, 1280, 640]","[2560, 1280, 1280, 1280]","[2560, 1280]",105,True,0.259707,28
14,gat,16,0.794585,0.783274,0.806227,0.943236,0.888780,0.718494,32,0.000099,"[2560, 1280, 1280, 1280, 640]","[2560, 1280, 1280, 1280, 1280]","[2560, 2560, 2560, 1280]",94,True,0.568344,31
12,gat,14,0.791796,0.791651,0.791941,0.941748,0.888878,0.716012,32,0.000050,"[2560, 1280, 1280, 640]","[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280]",51,True,0.433603,18
31,gat,33,0.791719,0.778407,0.805495,0.943758,0.886923,0.714343,32,0.000074,"[2560, 1280, 1280, 640]","[2560, 1280, 1280, 1280]","[2560, 1280]",68,True,0.314862,14
23,gat,25,0.787104,0.796400,0.778022,0.940932,0.887705,0.710948,32,0.000082,"[2560, 1280]","[2560, 1280, 1280]","[2560, 1280]",84,True,0.300530,12
44,gat,46,0.783392,0.785846,0.780952,0.939781,0.884773,0.704909,64,0.000063,[640],"[2560, 1280]","[2560, 1280, 1280]",157,False,0.119496,11
43,gat,45,0.785050,0.766946,0.804029,0.939486,0.882525,0.704661,16,0.000073,"[2560, 1280]","[2560, 1280, 640]","[2560, 1280]",101,False,0.225198,14
35,gat,37,0.786436,0.738501,0.841026,0.940921,0.878127,0.704575,16,0.000095,"[2560, 1280]","[2560, 1280, 1280, 1280]","[2560, 1280]",138,True,0.356508,23
22,gat,24,0.782420,0.772776,0.792308,0.929888,0.882428,0.701991,32,0.000052,[2560],[2560],[1280],61,True,0.392393,18
15,gat,17,0.783295,0.751768,0.817582,0.939156,0.879300,0.701039,32,0.000119,"[2560, 1280, 640]","[2560, 1280, 1280, 1280, 640]","[1280, 640]",62,True,0.489943,20
41,gat,43,0.780897,0.777213,0.784615,0.939883,0.882525,0.700663,16,0.000091,"[2560, 2560, 2560, 1280]","[2560, 1280]","[2560, 1280]",88,False,0.284088,26
25,gat,27,0.779136,0.775881,0.782418,0.938278,0.881646,0.698313,32,0.000076,"[2560, 1280, 1280, 640]",[640],"[2560, 1280, 1280, 1280, 1280]",69,True,0.413822,25
33,gat,35,0.778161,0.770751,0.785714,0.934964,0.880473,0.696431,32,0.000094,"[1280, 640]","[2560, 1280]","[2560, 1280]",88,True,0.311748,12
19,gat,21,0.777321,0.759525,0.795971,0.936041,0.878323,0.694036,32,0.000076,"[2560, 1280]","[2560, 1280]","[2560, 1280]",79,True,0.543317,14
32,gat,34,0.776571,0.755455,0.798901,0.933239,0.877346,0.692647,32,0.000067,"[2560, 1280]","[2560, 1280]","[2560, 1280]",100,True,0.394102,9
24,gat,26,0.772711,0.763591,0.782051,0.936925,0.877248,0.688739,32,0.000130,"[2560, 1280, 1280, 640]","[2560, 2560, 2560, 1280]","[2560, 2560, 2560, 1280]",113,True,0.469660,20
39,gat,41,0.763823,0.793525,0.736264,0.933506,0.878518,0.683073,16,0.000053,"[2560, 1280, 1280]","[2560, 1280]","[2560, 1280, 1280]",131,False,0.127601,11
17,gat,19,0.764028,0.788919,0.740659,0.928543,0.877932,0.682428,32,0.000079,"[2560, 1280, 1280, 1280, 1280]",[1280],"[2560, 1280, 640]",75,True,0.460920,23
34,gat,36,0.764629,0.780832,0.749084,0.932982,0.876955,0.681652,32,0.000063,"[2560, 1280]","[2560, 640]","[2560, 1280]",119,True,0.427691,11
48,gat,50,0.761456,0.784687,0.739560,0.932589,0.876368,0.678658,32,0.000115,"[2560, 2560, 2560, 1280, 640]","[2560, 1280]","[2560, 2560, 2560, 1280, 640]",99,False,0.208176,20
45,gat,47,0.759489,0.792280,0.729304,0.933950,0.876759,0.677883,32,0.000089,"[2560, 1280]","[2560, 1280]","[2560, 1280]",93,False,0.342933,9
27,gat,29,0.758412,0.783594,0.734799,0.929809,0.875098,0.674940,32,0.000104,"[2560, 1280]","[2560, 1280]","[2560, 1280]",88,True,0.372443,12
26,gat,28,0.759626,0.775573,0.744322,0.925594,0.874316,0.674850,32,0.000065,"[2560, 1280]","[2560, 1280]","[2560, 1280]",54,True,0.516461,9
4,gat,6,0.756975,0.758646,0.755311,0.929448,0.870602,0.668806,16,0.000505,"[2560, 1280, 1280, 640]","[2560, 1280, 1280, 1280]",[2560],106,False,0.236462,39
47,gat,49,0.744792,0.756614,0.733333,0.925976,0.865911,0.654035,16,0.000140,"[2560, 1280]","[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280]",78,True,0.372608,23
20,gat,22,0.735529,0.785923,0.691209,0.921350,0.867377,0.649890,32,0.000173,"[2560, 1280]","[2560, 1280, 1280, 640]",[640],96,True,0.694675,20
49,gat,51,0.742287,0.735612,0.749084,0.924892,0.861220,0.647389,64,0.000050,"[2560, 1280, 1280, 640]","[2560, 1280]","[2560, 1280]",120,True,0.265028,6
42,gat,44,0.728003,0.806050,0.663736,0.924240,0.867670,0.646935,16,0.000051,"[2560, 1280]","[2560, 1280]","[2560, 1280]",113,False,0.337090,7
46,gat,48,0.724776,0.724643,0.724908,0.913775,0.853108,0.624596,32,0.000063,"[2560, 1280]","[2560, 1280]","[2560, 1280]",62,True,0.440415,6
16,gat,18,0.721114,0.741486,0.701832,0.913544,0.855160,0.623821,32,0.000118,"[2560, 1280]","[1280, 640]","[2560, 640]",94,True,0.634096,10
30,gat,32,0.703052,0.784393,0.636996,0.910628,0.856431,0.615463,64,0.000168,"[2560, 1280]","[2560, 1280]","[2560, 1280]",121,True,0.167941,8
36,gat,38,0.695207,0.788569,0.621612,0.913720,0.854574,0.608802,32,0.000132,"[2560, 1280]","[2560, 1280]","[2560, 1280]",70,False,0.496394,7
5,gat,7,0.696804,0.744380,0.654945,0.906489,0.847928,0.598044,32,0.000344,"[2560, 640]","[2560, 1280]",[2560],193,False,0.587494,10
8,gat,10,0.677822,0.803616,0.586081,0.901344,0.851349,0.596560,64,0.000250,[640],"[2560, 1280]",[2560],147,False,0.040616,5
18,gat,20,0.664379,0.801345,0.567399,0.900469,0.847048,0.583270,32,0.000176,[1280],"[2560, 1280]","[2560, 1280, 1280, 640]",111,True,0.198685,9
1,gat,3,0.653209,0.777834,0.563004,0.888343,0.840500,0.565250,64,0.001077,"[1280, 640]","[2560, 1280]","[2560, 1280, 1280]",149,False,0.321981,12
40,gat,42,0.627372,0.803316,0.514652,0.892429,0.836884,0.550789,16,0.000358,"[2560, 1280, 1280, 1280]","[2560, 2560, 2560, 1280, 640]","[2560, 1280]",105,False,0.232798,23
3,gat,5,0.542677,0.802726,0.409890,0.850289,0.815676,0.481218,16,0.001255,"[2560, 1280, 1280]","[2560, 2560, 2560, 1280, 640]","[2560, 2560, 2560, 1280, 640]",128,True,0.792299,24
6,gat,8,0.476215,0.831204,0.333700,0.857006,0.804144,0.441978,64,0.000658,"[2560, 640]","[2560, 1280, 640]","[2560, 1280]",187,False,0.693985,6
0,gat,2,0.473241,0.731240,0.349817,0.798268,0.792220,0.401656,64,0.000547,"[2560, 1280]","[2560, 1280]","[2560, 1280, 1280]",141,True,0.826341,3
9,gat,11,0.296296,0.941176,0.175824,0.804231,0.777170,0.349216,16,0.000221,"[2560, 2560, 2560, 1280, 640]","[2560, 1280]","[2560, 1280, 1280, 1280]",128,False,0.779245,8
2,gat,4,0.000732,0.500000,0.000366,0.520191,0.733190,0.007372,16,0.001070,"[2560, 2560, 2560, 1280]","[2560, 640]","[2560, 1280]",155,False,0.887857,4
7,gat,9,0.000000,0.000000,0.000000,0.486678,0.733190,0.000000,64,0.002665,"[2560, 1280, 1280, 1280]","[2560, 1280]","[2560, 1280, 1280, 1280, 640]",173,True,0.950252,10