In [51]:
import pandas as pd


rhea = pd.read_csv("RHEA_final_dataset_random.csv")
rhea_positives = rhea[rhea["interaction"]==1]

/tmp/ipykernel_2115328/1263291288.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  rhea = pd.read_csv("RHEA_final_dataset_random.csv")

In [52]:
rhea_positives

# Rename columns
rhea_positives = rhea_positives.rename(columns={'uniprot_id': 'Enzyme ID', 'CHEBI_ID': 'Substrate ID', "interaction":"Binding",
                                                "sequence":"Sequence"})

In [53]:
dataset = pd.read_csv("../dataset_integration/integrated_dataset.csv").drop_duplicates(subset=["Enzyme ID", "Substrate ID"], keep="first")
dataset["Validated"] = True
dataset["Validated"].value_counts()

True    76471
Name: Validated, dtype: int64

In [54]:
rhea_positives["Validated"] = False
rhea_positives["Validated"].value_counts()

False    214140
Name: Validated, dtype: int64

In [55]:
pd.concat([dataset, rhea_positives], axis=0)

,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,pubchem_id,Validated,RHEA_ID,EC number,reaction_SMILES
0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,True,NaN,NaN,NaN
1,MDYVTLASHAVRQYAPDQIFTASQRAKADAAALGEDAVINATLGEC...,C(C(=O)O)N,0.0,A0A174XK40,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,True,NaN,NaN,NaN
2,MFQKVDAYAGDPILTLMERFKEDPRSDKVNLSIGLYYNEDGIIPQL...,C(C(=O)O)N,0.0,P04693,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,True,NaN,NaN,NaN
3,MFQKVDAYAGDPILSLMERFKEDPRSDKVNLSIGLYYNDDGIIPQL...,C(C(=O)O)N,0.0,A0A3N0RMA5,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,True,NaN,NaN,NaN
4,MSPIEKSSKLENVCYDIRGPVLKEAKRLEEEGNKVLKLNIGNPAPF...,C(C(=O)O)N,0.0,P0A959,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
214135,MNREDVEFPTCDGLILRGWLYPGTIRGPAIVMNQGFNTPKEILLPD...,*N[C@@H](COP(=O)([O-])OCC(C)(C)[C@@H](O)C(=O)N...,1.0,Q4WAY4,CHEBI:193519,NaN,NaN,False,RHEA:74751.0,2.3.1.-,[H][C@]1([C@@]2(C)O[C@]2([H])CC=C(C)C)[C@H](OC...
214136,MSEKLDSYKLMQEHQTWTSKPASLEEWQIVNEWAIAEKWDLGLGDT...,C/C(=C\C(=O)OCCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H...,1.0,F8J3H2,CHEBI:142976,NaN,NaN,False,RHEA:75895.0,2.3.1.-,C/C(=C\C(=O)OCCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H...
214137,MSEKLDSYKLMQEHQTWTSKPASLEEWQIVNEWAIAEKWDLGLGDT...,Nc1c2sscc-2[nH]c1=O,1.0,F8J3H2,CHEBI:194488,NaN,NaN,False,RHEA:75895.0,2.3.1.-,C/C(=C\C(=O)OCCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H...
214138,MAANGKVVSEMIAWIKSQKLIAPRMKDAPTFYRNLEEALDVRRSTQ...,[NH3+]C(C(=O)[O-])C(=O)[O-],1.0,B0XZV7,CHEBI:58158,NaN,NaN,False,RHEA:81151.0,2.3.1.-,[NH3+]C(C(=O)[O-])C(=O)[O-].*N[C@@H](COP(=O)([...
214139,MAANGKVVSEMIAWIKSQKLIAPRMKDAPTFYRNLEEALDVRRSTQ...,*N[C@@H](COP(=O)([O-])OCC(C)(C)[C@@H](O)C(=O)N...,1.0,B0XZV7,CHEBI:231803,NaN,NaN,False,RHEA:81151.0,2.3.1.-,[NH3+]C(C(=O)[O-])C(=O)[O-].*N[C@@H](COP(=O)([...

In [56]:
dataset = pd.concat([dataset, rhea_positives], axis=0).drop_duplicates(subset=["Enzyme ID", "Substrate ID"], keep="first")

In [57]:
dataset["Validated"].value_counts()

False    200367
True      76471
Name: Validated, dtype: int64

In [58]:
train_dataset = pd.read_csv("ESP_train_df.csv")
validation_dataset = pd.read_csv("ESP_val_df.csv")
test_dataset = pd.read_csv("ESP_test_df.csv")

dataset_prosmith = pd.concat([train_dataset, validation_dataset, test_dataset])
dataset_prosmith["Validated"] = False

In [59]:
dataset_prosmith = dataset_prosmith.rename(columns={'Uniprot ID': 'Enzyme ID', 'molecule ID': 'Substrate ID', "output":"Binding",
                                                "Protein sequence":"Sequence"})
dataset_prosmith

,Enzyme ID,Substrate ID,Binding,Sequence,SMILES,Validated
0,Q5B2F7,CHEBI:57344,1,MQNSTKTVRIVEVGPRDGLQNIPQSIDSTIKLDLIRRLRDAGLQTI...,CC(C)=CC(=O)SCCN=C([O-])CCN=C([O-])[C@H](O)C(C...,False
1,Q9SAH9,CHEBI:58349,1,MLVDGKLVCVTGAGGYIASWIVKLLLERGYTVRGTVRNPTDPKNNH...,N=C([O-])c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(...,False
2,Q8IPJ6,CHEBI:57776,1,MTDYLSLHSRLAQVGQEHLLKFWPELTNDERIDLVRDIEELNLDEI...,CC([O-])=N[C@H]1[C@@H](OP(=O)([O-])O)O[C@H](CO...,False
3,A0A1D5PCZ1,C00002,1,MAEPPAAPGPEGEEGPVRFARKGALRQKNVHEVKNHKFTARFFKQP...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O...,False
4,O22765,CHEBI:33384,1,MDLLKTPSSTVGLSETFARLKSQGKVALIPYITAGDPDLSTTAKAL...,N[C@@H](CO)C(=O)O,False
...,...,...,...,...,...,...
13331,P48163,CHEBI:30616,0,MEPEAPRRRHTHQRGYLLTRNPHLNKDLAFTLEERQQLNIHGLLPP...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])OP(=O...,False
13332,P48163,C00002,0,MEPEAPRRRHTHQRGYLLTRNPHLNKDLAFTLEERQQLNIHGLLPP...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O...,False
13333,Q3TIG7,CHEBI:16389,0,DGLRGGGRFFHGLAWILEEPWSSWFILNLKTTAEEEKEEVESLKSI...,COC1=C(OC)C(=O)C(CC=C(C)C)=C(C)C1=O,False
13334,Q3TIG7,CHEBI:57925,0,DGLRGGGRFFHGLAWILEEPWSSWFILNLKTTAEEEKEEVESLKSI...,N[C@@H](CCC([O-])=N[C@@H](CS)C(O)=NCC(=O)O)C(=O)O,False
13335,Q3TIG7,CHEBI:16469,0,DGLRGGGRFFHGLAWILEEPWSSWFILNLKTTAEEEKEEVESLKSI...,C[C@]12CC[C@@H]3c4ccc(O)cc4CC[C@H]3[C@@H]1CC[C...,False

In [60]:
dataset = pd.concat([dataset, dataset_prosmith], axis=0).drop_duplicates(subset=["Enzyme ID", "Substrate ID"], keep="first")
dataset

,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,pubchem_id,Validated,RHEA_ID,EC number,reaction_SMILES
0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,True,NaN,NaN,NaN
1,MDYVTLASHAVRQYAPDQIFTASQRAKADAAALGEDAVINATLGEC...,C(C(=O)O)N,0.0,A0A174XK40,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,True,NaN,NaN,NaN
2,MFQKVDAYAGDPILTLMERFKEDPRSDKVNLSIGLYYNEDGIIPQL...,C(C(=O)O)N,0.0,P04693,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,True,NaN,NaN,NaN
3,MFQKVDAYAGDPILSLMERFKEDPRSDKVNLSIGLYYNDDGIIPQL...,C(C(=O)O)N,0.0,A0A3N0RMA5,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,True,NaN,NaN,NaN
4,MSPIEKSSKLENVCYDIRGPVLKEAKRLEEEGNKVLKLNIGNPAPF...,C(C(=O)O)N,0.0,P0A959,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
13331,MEPEAPRRRHTHQRGYLLTRNPHLNKDLAFTLEERQQLNIHGLLPP...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])OP(=O...,0.0,P48163,CHEBI:30616,NaN,NaN,False,NaN,NaN,NaN
13332,MEPEAPRRRHTHQRGYLLTRNPHLNKDLAFTLEERQQLNIHGLLPP...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O...,0.0,P48163,C00002,NaN,NaN,False,NaN,NaN,NaN
13333,DGLRGGGRFFHGLAWILEEPWSSWFILNLKTTAEEEKEEVESLKSI...,COC1=C(OC)C(=O)C(CC=C(C)C)=C(C)C1=O,0.0,Q3TIG7,CHEBI:16389,NaN,NaN,False,NaN,NaN,NaN
13334,DGLRGGGRFFHGLAWILEEPWSSWFILNLKTTAEEEKEEVESLKSI...,N[C@@H](CCC([O-])=N[C@@H](CS)C(O)=NCC(=O)O)C(=O)O,0.0,Q3TIG7,CHEBI:57925,NaN,NaN,False,NaN,NaN,NaN
13335,DGLRGGGRFFHGLAWILEEPWSSWFILNLKTTAEEEKEEVESLKSI...,C[C@]12CC[C@@H]3c4ccc(O)cc4CC[C@H]3[C@@H]1CC[C...,0.0,Q3TIG7,CHEBI:16469,NaN,NaN,False,NaN,NaN,NaN

In [61]:
dataset[dataset["Validated"]==False].Binding.value_counts()

0.0    554910
1.0    384050
Name: Binding, dtype: int64

In [62]:
len(dataset[dataset["Validated"]==False]["Substrate ID"].unique())

3517

In [63]:
len(dataset[dataset["Validated"]==False]["Enzyme ID"].unique())

279641

In [64]:
dataset[dataset["Validated"]==False].to_csv("augmented_dataset_not_validated.csv", index=False)

In [65]:
dataset.drop_duplicates(subset=["Sequence"]).loc[:, ["Sequence", "Enzyme ID"]].sample(frac=1).to_csv("unique_enzymes.csv", index=False)

In [66]:
import csv

def csv_to_fasta(csv_file_path, fasta_file_path):
    with open(csv_file_path, mode='r', newline='') as csv_file, open(fasta_file_path, mode='w') as fasta_file:
        csv_reader = csv.reader(csv_file)
        next(csv_reader)  # Skip the header row if there is one

        for row in csv_reader:
            if len(row) >= 2:
                sequence_id = row[1].replace(" ", "_")
                sequence = row[0]
                fasta_file.write(f">{sequence_id}\n")
                fasta_file.write(f"{sequence}\n")

# Example usage
csv_file_path = 'unique_enzymes.csv'  # Path to your CSV file
fasta_file_path = 'unique_enzymes.fasta'  # Path to save the FASTA file
csv_to_fasta(csv_file_path, fasta_file_path)