In [53]:

from Bio import SeqIO

def read_fasta(file_path):
    sequences = {}
    for record in SeqIO.parse(file_path, "fasta"):
        sequences[record.id] = str(record.seq)
    return sequences

# Example usage
file_path = 'all_sequences_clustered_sequences_60.fasta'
sequences = read_fasta(file_path)

In [2]:
import pandas as pd

dataset = pd.read_csv("augmented_dataset_not_validated.csv")
dataset.shape

/tmp/ipykernel_2871384/2318882957.py:3: DtypeWarning: Columns (8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv("augmented_dataset_not_validated.csv")

(938960, 11)

In [56]:
# Example usage
file_path = 'all_sequences_clustered_sequences_60.fasta'
sequences = read_fasta(file_path)
dataset_60 = dataset[dataset["Enzyme ID"].isin(sequences.keys())]

In [57]:
len(dataset_60["Enzyme ID"].unique())

72306

In [58]:
len(dataset_60["Substrate ID"].unique())

3162

In [3]:
validated_dataset = pd.read_csv("../dataset_integration/integrated_dataset_descriptors_available.csv")
# validated_dataset = validated_dataset[validated_dataset["Validated"]==True]
validated_dataset

,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,pubchem_id
0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0
1,MDYVTLASHAVRQYAPDQIFTASQRAKADAAALGEDAVINATLGEC...,C(C(=O)O)N,0.0,A0A174XK40,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0
2,MFQKVDAYAGDPILTLMERFKEDPRSDKVNLSIGLYYNEDGIIPQL...,C(C(=O)O)N,0.0,P04693,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0
3,MFQKVDAYAGDPILSLMERFKEDPRSDKVNLSIGLYYNDDGIIPQL...,C(C(=O)O)N,0.0,A0A3N0RMA5,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0
4,MSPIEKSSKLENVCYDIRGPVLKEAKRLEEEGNKVLKLNIGNPAPF...,C(C(=O)O)N,0.0,P0A959,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0
...,...,...,...,...,...,...,...
74303,MKYRAVTLESFGYQLAPVVVSTSDLEARLEPLYRQLRIAPGQLQAM...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Pelobacter_propionicus,benzoate,https://doi.org/10.1093/synbio/ysaa004,70396.0
74304,MAFLSVNNVEIVGLAAAVPKNVETLDNLEFFAPGEAEKVMALTGIK...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Bacteroides_luti,benzoate,https://doi.org/10.1093/synbio/ysaa004,70396.0
74305,MSAPRYSQVSAVAVRLPDEDLTTPELEELLAERNPRVDVPRGLIER...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Nonomuraea_candida,benzoate,https://doi.org/10.1093/synbio/ysaa004,70396.0
74306,MRYQRVFINKIAYELPKEKVATSFLEEQLTDVYQELGIPLGQVEAL...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Legionella_brunensis,benzoate,https://doi.org/10.1093/synbio/ysaa004,70396.0
74307,MTYSRIGQIAVHLPEGGRTSAEVEALVAELNPGFEPPEGLIERFTG...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Allokutzneria_albata,benzoate,https://doi.org/10.1093/synbio/ysaa004,70396.0

In [60]:
augmented_dataset = pd.concat([validated_dataset, dataset_60], axis=0)

In [61]:
augmented_dataset

/home/jcapela/miniconda3/envs/esp/lib/python3.10/site-packages/IPython/lib/pretty.py:787: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  output = repr(obj)
/home/jcapela/miniconda3/envs/esp/lib/python3.10/site-packages/IPython/core/formatters.py:347: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  return method()

,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,pubchem_id,Validated,RHEA_ID,EC number,reaction_SMILES
0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,NaN,NaN,NaN,NaN
1,MDYVTLASHAVRQYAPDQIFTASQRAKADAAALGEDAVINATLGEC...,C(C(=O)O)N,0.0,A0A174XK40,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,NaN,NaN,NaN,NaN
2,MFQKVDAYAGDPILTLMERFKEDPRSDKVNLSIGLYYNEDGIIPQL...,C(C(=O)O)N,0.0,P04693,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,NaN,NaN,NaN,NaN
3,MFQKVDAYAGDPILSLMERFKEDPRSDKVNLSIGLYYNDDGIIPQL...,C(C(=O)O)N,0.0,A0A3N0RMA5,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,NaN,NaN,NaN,NaN
4,MSPIEKSSKLENVCYDIRGPVLKEAKRLEEEGNKVLKLNIGNPAPF...,C(C(=O)O)N,0.0,P0A959,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,750.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
938947,MAGHHHEHEQERDHEQEHEHDSLQRPTTGSERTRSISFSKLLTRSW...,N[C@@H](CCC([O-])=N[C@@H](CS)C(O)=NCC(=O)O)C(=O)O,0.0,P53739,CHEBI:57925,NaN,NaN,False,NaN,NaN,NaN
938948,MAGHHHEHEQERDHEQEHEHDSLQRPTTGSERTRSISFSKLLTRSW...,COC1=C(OC)C(=O)C(CC=C(C)C)=C(C)C1=O,0.0,P53739,CHEBI:16389,NaN,NaN,False,NaN,NaN,NaN
938949,MQTSLANIVLFSSLQVLLSLTCFQEVVEAASGKGFGDNIHWRTLDD...,CCCCC[C@H](O)/C=C/[C@@H]1[C@@H](C/C=C\CCCC(=O)...,0.0,H9D1R1,CHEBI:57405,NaN,NaN,False,NaN,NaN,NaN
938950,MQTSLANIVLFSSLQVLLSLTCFQEVVEAASGKGFGDNIHWRTLDD...,C[C@]12CC[C@@H]3c4ccc(O)cc4CC[C@H]3[C@@H]1CC[C...,0.0,H9D1R1,CHEBI:16469,NaN,NaN,False,NaN,NaN,NaN
938951,MQTSLANIVLFSSLQVLLSLTCFQEVVEAASGKGFGDNIHWRTLDD...,C=C(O[C@@H]1C=C(C(=O)[O-])C=C[C@H]1O)C(=O)[O-],0.0,H9D1R1,CHEBI:29748,NaN,NaN,False,NaN,NaN,NaN

In [77]:
len(augmented_dataset["Enzyme ID"].unique())

78512

In [78]:
len(augmented_dataset["Substrate ID"].unique())

3196

In [79]:
augmented_dataset["Binding"].value_counts()

0.0    210296
1.0    101447
Name: Binding, dtype: int64

In [68]:
unique_compounds_w_descriptors = pd.read_csv("../dataset_integration/unique_compounds_with_features.csv")

In [73]:
augmented_dataset = augmented_dataset[augmented_dataset["Substrate ID"].isin(unique_compounds_w_descriptors.ids)]
augmented_dataset.to_csv("augmented_Dataset_60.csv", index=False)

In [72]:
len(augmented_dataset["Substrate ID"].unique())

3196

In [74]:
augmented_dataset.drop_duplicates(subset=["Sequence"]).loc[:, ["Sequence", "Enzyme ID"]].sample(frac=1).to_csv("unique_enzymes.csv", index=False)

In [75]:
pd.read_csv("unique_enzymes.csv")

                                                Sequence Enzyme ID
0      MLKVKTLSKNATEPKRATENAAGYDLSSAKNLIVPAGGTALVQTDI...    F0ZQA7
1      MRAVCVIKGENIDGNIFFNQINKESPVYIEGIINGLKPGIHAFQIN...    F1A3R8
2      MVPASILDMGQDCAGVLSSTDSEFPVSEVLVEFCALCRRYVAAENR...    C3YIR4
3      MTFLEFLKEFFSWRDILDIFGLFLFFYLFIRFLYIAKGLYILRLLI...    O67447
4      MIVTRFAPSPTGYLHIGGLRTALFSYLWARKNGGKFLLRIEDTDKA...    Q30UA5
...                                                  ...       ...
78475  MDQDAIFDEECDYLFKAVLIGDSGVGKSNLLSRFAKDEFRLDSKPT...    G7LDC2
78476  MALVTTTPTVNDEPLFAEVDMASYFTSTTVRATVVQASTIFYDTPA...    Q3LRV4
78477  MSQIMSGEEEKLQEIPDMDTLVRELRRIYQGQEVNVEEVKDVLSRY...    T1FPC2
78478  MASQLTDAFARKFYYLRLSITDVCNFRCTYCLPDGYKPSGVTNKGF...    P30745
78479  MARLTVITTGGTISTTAGPDGVLRPTHCGATLIAGLDMDSDIEVVD...    P63628

[78480 rows x 2 columns]

In [76]:
import csv

def csv_to_fasta(csv_file_path, fasta_file_path):
    with open(csv_file_path, mode='r', newline='') as csv_file, open(fasta_file_path, mode='w') as fasta_file:
        csv_reader = csv.reader(csv_file)
        next(csv_reader)  # Skip the header row if there is one

        for row in csv_reader:
            if len(row) >= 2:
                sequence_id = row[1].replace(" ", "_")
                sequence = row[0]
                fasta_file.write(f">{sequence_id}\n")
                fasta_file.write(f"{sequence}\n")

# Example usage
csv_file_path = 'unique_enzymes.csv'  # Path to your CSV file
fasta_file_path = 'unique_enzymes.fasta'  # Path to save the FASTA file
csv_to_fasta(csv_file_path, fasta_file_path)