In [16]:
import pandas as pd
curated_dataset = pd.read_csv("curated_dataset.csv")

In [2]:
curated_dataset["Binding"].value_counts()

0.0    48190
1.0    25040
Name: Binding, dtype: int64

In [3]:
len(curated_dataset["Substrate ID"].unique())

1728

In [ ]:
len(curated_dataset["Enzyme ID"].unique())

10324

In [ ]:
test = curated_dataset.drop_duplicates(subset=["Enzyme ID"]).loc[:, ["Sequence", "Enzyme ID"]]
test.to_csv("")

,Sequence,Enzyme ID
0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,P00509
18,MDYVTLASHAVRQYAPDQIFTASQRAKADAAALGEDAVINATLGEC...,A0A174XK40
36,MFQKVDAYAGDPILTLMERFKEDPRSDKVNLSIGLYYNEDGIIPQL...,P04693
54,MFQKVDAYAGDPILSLMERFKEDPRSDKVNLSIGLYYNDDGIIPQL...,A0A3N0RMA5
72,MSPIEKSSKLENVCYDIRGPVLKEAKRLEEEGNKVLKLNIGNPAPF...,P0A959
...,...,...
72203,MKYRAVTLESFGYQLAPVVVSTSDLEARLEPLYRQLRIAPGQLQAM...,Pelobacter_propionicus
72204,MAFLSVNNVEIVGLAAAVPKNVETLDNLEFFAPGEAEKVMALTGIK...,Bacteroides_luti
72205,MSAPRYSQVSAVAVRLPDEDLTTPELEELLAERNPRVDVPRGLIER...,Nonomuraea_candida
72206,MRYQRVFINKIAYELPKEKVATSFLEEQLTDVYQELGIPLGQVEAL...,Legionella_brunensis
72207,MTYSRIGQIAVHLPEGGRTSAEVEALVAELNPGFEPPEGLIERFTG...,Allokutzneria_albata

In [24]:
test[test.duplicated(subset=["Sequence"])]

                                                Sequence   Enzyme ID
54489  MKPENKLPVLDLISAEMKTVVNTLQPDLPPWPATGTIAEQRQYYTL...      C4ZUT0
55523  MHHPVAPVIDTVVNLAKRRGFVYPSGEIYGGTKSAWDYGPLGVELK...      P9WFV7
56285  MRTAFELVAWSAHRQPGAVALLDPESGHRLTYSELLKRIEGVATVL...      P86831
56324  MDFSNMSILHYLANIVDILVVWFVIYKVIMLIRGTKAVQLLKGIFI...  A0A0H3GM48
56351  MPNIKIFSGSSHQDLSQKIADRLGLELGKVVTKKFSNQETCVEIGE...      P60892
...                                                  ...         ...
69496  MEKSNGLRVILFPLPLQGCINPMIQLAKILHSRGFSITVIHTCFNA...     UGT76C4
69499  MTKPSDPTRDSHVAVLAFPFGTHAAPLLTVTRRLASASPSTVFSFF...     UGT78D2
69501  MSQTTTNPHVAVLAFPFSTHAAPLLAVVRRLAAAAPHAVFSFFSTS...       VVGT1
69505  MKTAELIFVPLPETGHLLSTIEFGKRLLNLDRRISMITILSMNLPY...     UGT71C5
69522  MGSDHHHRKLHVMFFPFMAYGHMIPTLDMAKLFSSRGAKSTILTTS...     UGT73B2

[63 rows x 2 columns]

In [ ]:
import pandas as pd
10324
augmented_dataset = pd.read_csv("augmented_dataset_not_validated.csv")
augmentation = augmented_dataset[augmented_dataset["Validated"]==False]

augmentation

/tmp/ipykernel_153094/2608830630.py:3: DtypeWarning: Columns (7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  augmented_dataset = pd.read_csv("augmented_dataset_not_validated.csv")

,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,Validated,RHEA_ID,EC number,reaction_SMILES
0,MSSKLATPLSIQGEVIYPDDSGFDAIANIWDGRHLQRPSLIARCLS...,C[NH+]1CCC[C@@H]1c1ccc(O)nc1,1.0,P08159,CHEBI:58413,NaN,False,RHEA:10012.0,1.5.3.6,[H][C@]1(C2=CN=C(O)C=C2)CCC[NH+]1C.O=O.[H]O[H]...
1,MATNNIVVLGAGVSGLTTAWLLSKDPSNKITVAAKHMPGDYDIEYC...,[NH3+][C@H](CCC(=O)[O-])C(=O)[O-],1.0,A0A499UB99,CHEBI:29986,NaN,False,RHEA:10028.0,1.4.3.15,[NH3+][C@H](CCC(=O)[O-])C(=O)[O-].O=O.[H]O[H]>...
2,MATNNIVVLGAGVSGLTTAWLLSKDPSNKITVAAKHMPGDYDIEYC...,C[C@@H]([NH3+])C(=O)[O-],1.0,A0A499UB99,CHEBI:57416,NaN,False,RHEA:22688.0,1.4.3.19,C[C@@H]([NH3+])C(=O)[O-].O=O.[H]O[H]>>CC(=O)C(...
3,MATNNIVVLGAGVSGLTTAWLLSKDPSNKITVAAKHMPGDYDIEYC...,*[C@@H]([NH3+])C(=O)[O-],1.0,A0A499UB99,CHEBI:59871,NaN,False,RHEA:21816.0,1.4.3.3,*[C@@H]([NH3+])C(=O)[O-].O=O.[H]O[H]>>[1*]C(=O...
4,MATNNIVVLGAGVSGLTTAWLLSKDPSNKITVAAKHMPGDYDIEYC...,[NH3+]CCCC[C@@H]([NH3+])C(=O)[O-],1.0,A0A499UB99,CHEBI:32557,NaN,False,RHEA:37583.0,1.4.3.3,[NH3+]CCCC[C@@H]([NH3+])C(=O)[O-].O=O.[H]O[H]>...
...,...,...,...,...,...,...,...,...,...,...
938955,MEPEAPRRRHTHQRGYLLTRNPHLNKDLAFTLEERQQLNIHGLLPP...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])OP(=O...,0.0,P48163,CHEBI:30616,NaN,False,NaN,NaN,NaN
938956,MEPEAPRRRHTHQRGYLLTRNPHLNKDLAFTLEERQQLNIHGLLPP...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O...,0.0,P48163,C00002,NaN,False,NaN,NaN,NaN
938957,DGLRGGGRFFHGLAWILEEPWSSWFILNLKTTAEEEKEEVESLKSI...,COC1=C(OC)C(=O)C(CC=C(C)C)=C(C)C1=O,0.0,Q3TIG7,CHEBI:16389,NaN,False,NaN,NaN,NaN
938958,DGLRGGGRFFHGLAWILEEPWSSWFILNLKTTAEEEKEEVESLKSI...,N[C@@H](CCC([O-])=N[C@@H](CS)C(O)=NCC(=O)O)C(=O)O,0.0,Q3TIG7,CHEBI:57925,NaN,False,NaN,NaN,NaN
938959,DGLRGGGRFFHGLAWILEEPWSSWFILNLKTTAEEEKEEVESLKSI...,C[C@]12CC[C@@H]3c4ccc(O)cc4CC[C@H]3[C@@H]1CC[C...,0.0,Q3TIG7,CHEBI:16469,NaN,False,NaN,NaN,NaN

In [ ]:
augmentation["Binding"].value_counts()

0.0    554910
1.0    384050
Name: Binding, dtype: int64

In [7]:
len(augmentation["Enzyme ID"].unique())

279641

In [8]:
len(augmentation["Substrate ID"].unique())

3517

In [11]:
import pandas as pd

augmented_dataset = pd.read_csv("augmented_dataset_descriptors_available.csv")
augmentation = augmented_dataset

augmentation

/tmp/ipykernel_153094/2877589474.py:3: DtypeWarning: Columns (6,8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  augmented_dataset = pd.read_csv("augmented_dataset_descriptors_available.csv")

,Unnamed: 0,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,Validated,RHEA_ID,EC number,reaction_SMILES
0,0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
1,1,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 2,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
2,2,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 3,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
3,3,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 4,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
4,4,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC[C@H](C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 5,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
592388,623398,MAGHHHEHEQERDHEQEHEHDSLQRPTTGSERTRSISFSKLLTRSW...,N[C@@H](CCC([O-])=N[C@@H](CS)C(O)=NCC(=O)O)C(=O)O,0.0,P53739,CHEBI:57925,NaN,False,NaN,NaN,NaN
592389,623399,MAGHHHEHEQERDHEQEHEHDSLQRPTTGSERTRSISFSKLLTRSW...,COC1=C(OC)C(=O)C(CC=C(C)C)=C(C)C1=O,0.0,P53739,CHEBI:16389,NaN,False,NaN,NaN,NaN
592390,623400,MQTSLANIVLFSSLQVLLSLTCFQEVVEAASGKGFGDNIHWRTLDD...,CCCCC[C@H](O)/C=C/[C@@H]1[C@@H](C/C=C\CCCC(=O)...,0.0,H9D1R1,CHEBI:57405,NaN,False,NaN,NaN,NaN
592391,623401,MQTSLANIVLFSSLQVLLSLTCFQEVVEAASGKGFGDNIHWRTLDD...,C[C@]12CC[C@@H]3c4ccc(O)cc4CC[C@H]3[C@@H]1CC[C...,0.0,H9D1R1,CHEBI:16469,NaN,False,NaN,NaN,NaN
592392,623402,MQTSLANIVLFSSLQVLLSLTCFQEVVEAASGKGFGDNIHWRTLDD...,C=C(O[C@@H]1C=C(C(=O)[O-])C=C[C@H]1O)C(=O)[O-],0.0,H9D1R1,CHEBI:29748,NaN,False,NaN,NaN,NaN

In [12]:
augmentation["Binding"].value_counts()

0.0    390323
1.0    202070
Name: Binding, dtype: int64

In [14]:
len(augmentation["Enzyme ID"].unique())

163435

In [15]:
len(augmentation["Substrate ID"].unique())

3277