In [20]:
import pandas as pd

overlapping_range = pd.read_csv("overlapping_range.csv")
overlapping_range

       pdb                              compound  energy
0     1AHG  compound_aminotransferase_dataset_10  -4.663
1     1AHG  compound_aminotransferase_dataset_14  -5.763
2     1AHG  compound_aminotransferase_dataset_16  -5.572
3     1AHG  compound_aminotransferase_dataset_17  -6.509
4     1AHG  compound_aminotransferase_dataset_18  -5.758
...    ...                                   ...     ...
1014  2B0C        compound_phospatase_dataset_92  -6.121
1015  2B0C        compound_phospatase_dataset_93  -6.055
1016  2B0C        compound_phospatase_dataset_97  -6.397
1017  2B0C        compound_phospatase_dataset_98  -6.109
1018  2B0C        compound_phospatase_dataset_99  -6.734

[1019 rows x 3 columns]

In [21]:
dataset = pd.read_csv("pdb_chemical_components_curated_dataset.csv")
dataset.replace({"PDB_ID": "pdb"}, inplace=True)
dataset

      Uniprot_ID PDB_ID nonpol_ID chem_comp
0         P00509   1AAM    1AAM_2       SO4
1         P00509   1AAW    1AAW_2       PLP
2         P00509   1AHE    1AHE_2       SO4
3         P00509   1AHE    1AHE_3       PLP
4         P00509   1AHF    1AHF_2       PLP
...          ...    ...       ...       ...
18059     P0AAB4   2IDB    2IDB_3       EDO
18060     P0AAB4   5M1D    5M1D_2        MN
18061     P0AAB4   5M1D    5M1D_3       4LU
18062     P0AAB4   5M1D    5M1D_4       NaN
18063     P0AAB4   5M1D    5M1D_5       SO4

[18064 rows x 4 columns]

In [22]:
# rename column 'PDB_ID' to 'pdb' (if present) and show the result
dataset.rename(columns={"PDB_ID": "pdb"}, inplace=True)

dataset = dataset.iloc[:, :2]

In [23]:
overlapping_range = pd.merge(overlapping_range, dataset, on="pdb", how="left")
overlapping_range.drop_duplicates(subset=["pdb", "compound"], inplace=True)
overlapping_range

       pdb                              compound  energy Uniprot_ID
0     1AHG  compound_aminotransferase_dataset_10  -4.663     P00509
2     1AHG  compound_aminotransferase_dataset_14  -5.763     P00509
4     1AHG  compound_aminotransferase_dataset_16  -5.572     P00509
6     1AHG  compound_aminotransferase_dataset_17  -6.509     P00509
8     1AHG  compound_aminotransferase_dataset_18  -5.758     P00509
...    ...                                   ...     ...        ...
2308  2B0C        compound_phospatase_dataset_92  -6.121     P0A8Y3
2310  2B0C        compound_phospatase_dataset_93  -6.055     P0A8Y3
2312  2B0C        compound_phospatase_dataset_97  -6.397     P0A8Y3
2314  2B0C        compound_phospatase_dataset_98  -6.109     P0A8Y3
2316  2B0C        compound_phospatase_dataset_99  -6.734     P0A8Y3

[1019 rows x 4 columns]

In [33]:
from plants_sm.io.pickle import write_pickle

pairs_to_select = list(zip(overlapping_range['Uniprot_ID'], overlapping_range['compound']))

write_pickle("pairs_to_select.pkl", pairs_to_select)

True

In [25]:
dataset = pd.read_csv("../curated_dataset_no_stereochemistry_duplicates.csv")

In [26]:
dataset

,Unnamed: 0,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,Validated,RHEA_ID,EC number,reaction_SMILES
0,0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
1,1,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 2,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
2,2,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 3,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
3,3,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 4,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
4,4,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC[C@H](C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 5,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
52131,76466,MKYRAVTLESFGYQLAPVVVSTSDLEARLEPLYRQLRIAPGQLQAM...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Pelobacter_propionicus,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
52132,76467,MAFLSVNNVEIVGLAAAVPKNVETLDNLEFFAPGEAEKVMALTGIK...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Bacteroides_luti,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
52133,76468,MSAPRYSQVSAVAVRLPDEDLTTPELEELLAERNPRVDVPRGLIER...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Nonomuraea_candida,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
52134,76469,MRYQRVFINKIAYELPKEKVATSFLEEQLTDVYQELGIPLGQVEAL...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Legionella_brunensis,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
52135,76470,MTYSRIGQIAVHLPEGGRTSAEVEALVAELNPGFEPPEGLIERFTG...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Allokutzneria_albata,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN

In [29]:
mask = dataset.apply(lambda row: (row['Enzyme ID'], row['Substrate ID']) in pairs_to_select, axis=1)

# Select only the matching rows
dataset_selected = dataset[mask]
dataset_selected

,Unnamed: 0,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,Validated,RHEA_ID,EC number,reaction_SMILES
40456,54342,MASRLLLNNGAKMPILGLGTWKSPPGQVTEAVKVAIDVGYRHIDCA...,N=C([O-])c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(...,1.0,P15121,CHEBI:57540,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
40457,54343,MASRLLLNNGAKMPILGLGTWKSPPGQVTEAVKVAIDVGYRHIDCA...,CC(C=CC=C(C)C=CC1=C(C)CCCC1(C)C)=CC=O,1.0,P15121,CHEBI:15035,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
40499,54406,METNFSFDSNLIVIIIITLFATRIIAKRFLSTPKMVSQETVAHVKD...,N[C@@H](CCC([O-])=N[C@@H](CS)C(O)=NCC(=O)O)C(=O)O,1.0,P17695,CHEBI:57925,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
40529,54453,MDSKYQCVKLNDGHFMPVLGFGTYAPAEVPKSKALEATKLAIEAGF...,c1ccc2c(c1)ccc1ccccc12,1.0,Q04828,C11422,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
40531,54455,MDSKYQCVKLNDGHFMPVLGFGTYAPAEVPKSKALEATKLAIEAGF...,O[C@@H]1C=CC=C[C@H]1O,1.0,Q04828,CHEBI:10702,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
48701,71461,MPSYTVTVATGSQWFAGTDDYIYLSLVGSAGCSEKHLLDKPFYNDF...,CCCCC/C=C\C/C=C\C/C=C\C/C=C\CCCC(=O)[O-],1.0,P09917,CHEBI:32395,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
48721,71482,MSRQSISLRFPLLLLLLSPSPVFSADPGAPAPVNPCCYYPCQHQGI...,CCCCC/C=C\C/C=C\C/C=C\C/C=C\CCCC(=O)[O-],1.0,P05979,CHEBI:32395,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
48802,71594,MRSLYLIVFIVISLVKASKSDDGFCSAPSIVESDEKTNPIYWKATN...,N=C(O)N[C@H](N)C(=O)O,1.0,Q8GXV5,CHEBI:59947,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
48819,71616,MITHFRQAIEETLPWLSSFGADPAGGMTRLLYSPEWLETQQQFKKR...,N=C(O)NC(NC(=N)O)C(=O)[O-],1.0,P77425,CHEBI:17536,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
48857,71668,MYEWLNALPKAELHLHLEGTLEPELLFALAERNRIALPWNDVETLR...,Nc1nc[nH]c2ncnc1-2,1.0,Q9I6Y4,CHEBI:16708,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN

In [30]:
dataset = pd.read_csv("../curated_dataset.csv")
mask = dataset.apply(lambda row: (row['Enzyme ID'], row['Substrate ID']) in pairs_to_select, axis=1)

# Select only the matching rows
dataset_selected = dataset[mask]
dataset_selected

,Unnamed: 0,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,Validated,RHEA_ID,EC number,reaction_SMILES
54300,54301,MNSILITGCNRGLGLGLVKALLNLPQPPQHLFTTCRNREQAKELED...,N=C([O-])c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(...,1.0,Q9W3H4,CHEBI:58349,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
54339,54341,MASRLLLNNGAKMPILGLGTWKSPPGQVTEAVKVAIDVGYRHIDCA...,N=C([O-])c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(...,1.0,P15121,CHEBI:58349,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
54340,54342,MASRLLLNNGAKMPILGLGTWKSPPGQVTEAVKVAIDVGYRHIDCA...,N=C([O-])c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(...,1.0,P15121,CHEBI:57540,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
54341,54343,MASRLLLNNGAKMPILGLGTWKSPPGQVTEAVKVAIDVGYRHIDCA...,CC(C=CC=C(C)C=CC1=C(C)CCCC1(C)C)=CC=O,1.0,P15121,CHEBI:15035,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
54399,54401,MSYPEKFEGIAIQSHEDWKNPKKTKYDPKPFYDHDIDIKIEACGVC...,N=C([O-])c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(...,1.0,Q04894,CHEBI:58349,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
69002,71616,MITHFRQAIEETLPWLSSFGADPAGGMTRLLYSPEWLETQQQFKKR...,N=C(O)NC(NC(=N)O)C(=O)[O-],1.0,P77425,CHEBI:17536,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
69047,71663,MAATEDDRLAGSGEGERLDFLRDRHVRFFQRCLQVLPERYSSLETS...,CC(C)=CCC/C(C)=C/CC/C(C)=C/CC/C(C)=C/COP(=O)(O...,1.0,P53610,C00353,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
69052,71668,MYEWLNALPKAELHLHLEGTLEPELLFALAERNRIALPWNDVETLR...,Nc1nc[nH]c2ncnc1-2,1.0,Q9I6Y4,CHEBI:16708,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
69138,71761,MKAIAVKRGEDRPVVIEKPRPEPESGEALVRTLRVGVDGTDHEVIA...,OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O,1.0,Q977U7,C00221,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
69168,71800,MQWQTKLPLIAILRGITPDEALAHVGAVIDAGFDAVEIPLNSPQWE...,O=C([O-])C(=O)C[C@@H](O)[C@H](O)COP(=O)([O-])[O-],1.0,Q6BF16,CHEBI:58298,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN