In [1]:
import pandas as pd

In [2]:
mou = pd.read_pickle("Mou_df_GNN.pkl")

In [4]:
mou

,enzyme,metabolite,activity,ECFP,Sequence,ESM1b_ts,molecule ID,GNN rep
0,1a1,4-Aminobenzonitrile,0.716,0000000000000000000000000000000000100000000000...,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,"[0.9186029, -1.0484099, -0.13906932, 0.1101291...",4-Aminobenzonitrile,"[0.0, 145.14581, 68.23028, 1.6200383, 0.586062..."
1,1a1,4-Nitrophenylacetonitrile,0.000,0000000000001000000000000000000000000000000000...,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,"[0.9186029, -1.0484099, -0.13906932, 0.1101291...",4-Nitrophenylacetonitrile,"[0.0, 280.9636, 77.58315, 8.872483, 0.0, 0.0, ..."
2,1a1,4-(Dimethylamino)benzonitrile,4.363,0000000000000000000000000000000001100000000000...,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,"[0.9186029, -1.0484099, -0.13906932, 0.1101291...",4-(Dimethylamino)benzonitrile,"[0.6268362, 250.9972, 115.45758, 3.7945795, 2...."
3,1a1,4-Chlorobenzonitrile,3.998,0000000000000000000000000000000000100000000000...,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,"[0.9186029, -1.0484099, -0.13906932, 0.1101291...",4-Chlorobenzonitrile,"[0.0, 157.031, 95.45502, 1.9667053, 0.0, 0.0, ..."
4,1a1,"2,6-Dichlorobenzonitrile",0.000,0000000000000001000000000000000000000000000000...,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,"[0.9186029, -1.0484099, -0.13906932, 0.1101291...","2,6-Dichlorobenzonitrile","[106.52673, 194.76971, 202.29494, 3.9334106, 1..."
...,...,...,...,...,...,...,...,...
235,pmi28,Propionitrile,1.054,0000000000000000000000000000000001000000000000...,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,"[0.85646003, -1.1750039, -0.1453441, 0.1105357...",Propionitrile,"[2.467718, 49.35915, 10.034855, 5.220823, 1.19..."
236,pmi28,Benzoylacetonitrile,2.902,0000000000000000000000000000000000000000000000...,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,"[0.85646003, -1.1750039, -0.1453441, 0.1105357...",Benzoylacetonitrile,"[36.08793, 165.45912, 42.490715, 17.760801, 1...."
237,pmi28,Mandelonitrile,0.000,0100000000000000000000000000000000000000000000...,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,"[0.85646003, -1.1750039, -0.1453441, 0.1105357...",Mandelonitrile,"[0.8413251, 229.04993, 42.604652, 19.163635, 6..."
238,pmi28,Benzonitrile,4.580,0000000000000000000000000000000000100000000000...,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,"[0.85646003, -1.1750039, -0.1453441, 0.1105357...",Benzonitrile,"[0.0, 137.8894, 44.60862, 0.0, 0.0, 0.0, 0.200..."
239,pmi28,Acrylonitrile,0.845,0000000000000000000000000000000000000000000000...,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,"[0.85646003, -1.1750039, -0.1453441, 0.1105357...",Acrylonitrile,"[0.0, 35.269405, 0.36366546, 37.786404, 2.2417..."

In [19]:
import pandas as pd

# Specify the path to your Excel file
file_path = 'nitrilase_descriptors.xlsx'

# Read the Excel file
df = pd.read_excel(file_path)
df

,protein,nitrile class,nitriles,ZINC ID,activity,interface_delta_X,fa_atr,fa_elec,fa_rep,fa_sol,...,ISA,Xi,Ap,Phi,Psi,Pa,Pb,Pt,DGLJ,DGtor
0,1a1,Aromatic,4-Aminobenzonitrile,152697,0.000,-12.808,-17.008,-0.564,4.762,7.619,...,0.476,0.467,0.529,0.619,0.656,0.543,0.565,0.550,0.705,0.711
1,1a1,Arylaliphatic,4-Nitrophenylacetonitrile,154682,0.000,-12.572,-12.752,-0.501,1.421,6.467,...,0.475,0.470,0.528,0.614,0.664,0.539,0.567,0.549,0.695,0.703
2,1a1,Aromatic,4-(Dimethylamino)benzonitrile,155390,2.824,-11.979,-22.038,0.104,6.490,5.492,...,0.476,0.467,0.529,0.621,0.661,0.543,0.565,0.550,0.711,0.701
3,1a1,Aromatic,4-Chlorobenzonitrile,157255,5.477,-10.293,-18.752,-0.017,5.785,6.069,...,0.476,0.467,0.528,0.611,0.670,0.539,0.564,0.549,0.705,0.707
4,1a1,Aromatic,"2,6-Dichlorobenzonitrile",157318,0.000,-9.036,-11.809,-0.275,2.007,5.476,...,0.476,0.467,0.528,0.610,0.667,0.539,0.564,0.549,0.703,0.677
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,pmi28,Aliphatic,Propionitrile,6072456,0.705,-8.759,-9.723,-0.234,1.222,2.406,...,0.537,0.543,0.597,0.732,0.714,0.619,0.647,0.617,0.758,0.838
236,pmi28,Arylaliphatic,Benzoylacetonitrile,74119,3.185,-14.273,-17.885,-0.658,3.828,7.593,...,0.537,0.543,0.597,0.751,0.725,0.619,0.647,0.617,0.762,0.839
237,pmi28,Arylaliphatic,Mandelonitrile,8100870,0.000,-12.612,-15.573,-0.504,3.199,5.641,...,0.537,0.543,0.597,0.741,0.709,0.619,0.647,0.617,0.750,0.803
238,pmi28,Aromatic,Benzonitrile,899417,3.980,-11.982,-14.031,-0.371,1.994,4.744,...,0.537,0.543,0.597,0.736,0.706,0.619,0.647,0.617,0.760,0.814
239,pmi28,Aliphatic,Acrylonitrile,901212,0.856,-8.434,-8.313,-0.539,1.263,3.384,...,0.537,0.543,0.597,0.741,0.715,0.619,0.647,0.617,0.758,0.833

In [20]:
df = df.loc[:, ["protein", "nitriles", "ZINC ID", "activity"]]
df

    protein                       nitriles  ZINC ID  activity
0       1a1            4-Aminobenzonitrile   152697     0.000
1       1a1      4-Nitrophenylacetonitrile   154682     0.000
2       1a1  4-(Dimethylamino)benzonitrile   155390     2.824
3       1a1           4-Chlorobenzonitrile   157255     5.477
4       1a1       2,6-Dichlorobenzonitrile   157318     0.000
..      ...                            ...      ...       ...
235   pmi28                  Propionitrile  6072456     0.705
236   pmi28            Benzoylacetonitrile    74119     3.185
237   pmi28                 Mandelonitrile  8100870     0.000
238   pmi28                   Benzonitrile   899417     3.980
239   pmi28                  Acrylonitrile   901212     0.856

[240 rows x 4 columns]

In [21]:
from Bio import SeqIO

sequences = []

# Read the FASTA file
for record in SeqIO.parse("all_sequences_Mou.fasta", "fasta"):
    id_ = record.id
    sequence = str(record.seq)

    sequences.append(sequence)

In [22]:
import pandas as pd

compounds = pd.read_csv("nitrilases_compounds_smiles.csv", sep=" ")
compounds = compounds.loc[:, ["smiles", "source_label"]]
compounds.columns = ["SMILES", "ZINC ID"]

In [23]:
df["Enzyme_sequence"] = sequences

In [28]:
df

,protein,nitriles,ZINC ID,activity,Enzyme_sequence
0,1a1,4-Aminobenzonitrile,152697,0.000,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...
1,1a1,4-Nitrophenylacetonitrile,154682,0.000,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...
2,1a1,4-(Dimethylamino)benzonitrile,155390,2.824,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...
3,1a1,4-Chlorobenzonitrile,157255,5.477,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...
4,1a1,"2,6-Dichlorobenzonitrile",157318,0.000,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...
...,...,...,...,...,...
235,pmi28,Propionitrile,6072456,0.705,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...
236,pmi28,Benzoylacetonitrile,74119,3.185,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...
237,pmi28,Mandelonitrile,8100870,0.000,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...
238,pmi28,Benzonitrile,899417,3.980,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...
239,pmi28,Acrylonitrile,901212,0.856,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...

In [36]:
pd.merge(df, compounds, on="ZINC ID", how="left").drop_duplicates().to_csv("nitrilases_dataset.csv", index = False)

In [12]:
import pandas as pd

nitrilases = pd.read_csv("nitrilases_dataset.csv")
nitrilases

,protein,nitriles,ZINC ID,activity,Enzyme_sequence,SMILES
0,1a1,4-Aminobenzonitrile,152697,0.000,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,N#Cc1ccc(N)cc1
1,1a1,4-Nitrophenylacetonitrile,154682,0.000,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,N#CCc1ccc([N+](=O)[O-])cc1
2,1a1,4-(Dimethylamino)benzonitrile,155390,2.824,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,CN(C)c1ccc(C#N)cc1
3,1a1,4-Chlorobenzonitrile,157255,5.477,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,N#Cc1ccc(Cl)cc1
4,1a1,"2,6-Dichlorobenzonitrile",157318,0.000,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,N#Cc1c(Cl)cccc1Cl
...,...,...,...,...,...,...
235,pmi28,Propionitrile,6072456,0.705,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,CCC#N
236,pmi28,Benzoylacetonitrile,74119,3.185,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,N#CCC(=O)c1ccccc1
237,pmi28,Mandelonitrile,8100870,0.000,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,N#C[C@H](O)c1ccccc1
238,pmi28,Benzonitrile,899417,3.980,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,N#Cc1ccccc1
239,pmi28,Acrylonitrile,901212,0.856,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,C=CC#N

In [13]:
nitrilases.columns = ["Enzyme ID", "Substrate Name", "Substrate ID", "activity", "Sequence", "SMILES"]
nitrilases["Binding"] = [int(y > 2) for y in nitrilases["activity"]]
nitrilases

,Enzyme ID,Substrate Name,Substrate ID,activity,Sequence,SMILES,Binding
0,1a1,4-Aminobenzonitrile,152697,0.000,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,N#Cc1ccc(N)cc1,0
1,1a1,4-Nitrophenylacetonitrile,154682,0.000,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,N#CCc1ccc([N+](=O)[O-])cc1,0
2,1a1,4-(Dimethylamino)benzonitrile,155390,2.824,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,CN(C)c1ccc(C#N)cc1,1
3,1a1,4-Chlorobenzonitrile,157255,5.477,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,N#Cc1ccc(Cl)cc1,1
4,1a1,"2,6-Dichlorobenzonitrile",157318,0.000,TIVKAAAVQISPVLYSREGTVERVVKKIRELGEKGVQFATFPETVI...,N#Cc1c(Cl)cccc1Cl,0
...,...,...,...,...,...,...,...
235,pmi28,Propionitrile,6072456,0.705,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,CCC#N,0
236,pmi28,Benzoylacetonitrile,74119,3.185,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,N#CCC(=O)c1ccccc1,1
237,pmi28,Mandelonitrile,8100870,0.000,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,N#C[C@H](O)c1ccccc1,0
238,pmi28,Benzonitrile,899417,3.980,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,N#Cc1ccccc1,1
239,pmi28,Acrylonitrile,901212,0.856,MKIVKAAAVQISPVLYNREATVEKVVQKILELGQQGVQFATFPETV...,C=CC#N,0

In [14]:
nitrilases["Publication"] = ["https://doi.org/10.1002/prot.26019"] * nitrilases.shape[0]

In [15]:
nitrilases.to_csv("mou_data.csv", index=False)