In [1]:
import pandas as pd


phospatase = pd.read_csv("phosphatase_chiral_binary.csv")
phospatase.columns = ["Index", "Sequence", "SMILES", "Binding"]

In [2]:
import pandas as pd

phospatase_sequences = pd.read_csv("phosphatase_metadata/phosphatase_sequence_file.txt", sep="\t")
phospatase_sequences = phospatase_sequences.loc[:, ["Entry", "Sequence"]]

In [3]:
phospatase.shape

(35970, 4)

In [4]:
import numpy as np


phospatase = pd.merge(phospatase, phospatase_sequences, on="Sequence")
phospatase.columns = ["Index", "Sequence", "SMILES", "Binding", "Enzyme ID"]
# Check for None or NaN values
nan_mask = np.array([str(x).lower() == 'nan' for x in np.array(phospatase.loc[:, "Enzyme ID"])])

# Count the number of NaN values
nan_count = np.sum(nan_mask)
nan_count

0

In [5]:

def convert_dataset(phospatase, name):

    # Sample data: assuming phosphatase.Sequence.unique() returns a list of unique sequences
    unique_sequences = phospatase.SMILES.unique()

    # Create a dictionary with keys labeled as "phosphatase 1", "phosphatase 2", etc.
    phosphatase_compounds_dict = {seq: f"compound_{name}_dataset {i+1}" for i, seq in enumerate(unique_sequences)}

    compound_ids = []

    for i, row in phospatase.iterrows():
        smiles = row["SMILES"]
        compound_ids.append(phosphatase_compounds_dict[smiles])

    phospatase["Substrate ID"] = compound_ids
    return phospatase

In [6]:
phospatase = convert_dataset(phospatase, "phospatase")
phospatase

,Index,Sequence,SMILES,Binding,Enzyme ID,Substrate ID
0,0,MAAKGLLVMDVDSTLIEEEVIDLLGEKAGMGDKISEITAAAMSGEI...,C=C(OP(=O)(O)O)C(=O)O,0,Q9CHW3,compound_phospatase_dataset 1
1,1,MAAKGLLVMDVDSTLIEEEVIDLLGEKAGMGDKISEITAAAMSGEI...,CC(=O)N[C@@H]1C(O)O[C@H](COP(=O)(O)O)[C@@H](O)...,0,Q9CHW3,compound_phospatase_dataset 2
2,2,MAAKGLLVMDVDSTLIEEEVIDLLGEKAGMGDKISEITAAAMSGEI...,CC(=O)N[C@@H]1[C@@H](O)CC(O)(C(=O)O)O[C@H]1[C@...,0,Q9CHW3,compound_phospatase_dataset 3
3,3,MAAKGLLVMDVDSTLIEEEVIDLLGEKAGMGDKISEITAAAMSGEI...,CC(=O)OP(=O)(O)O,0,Q9CHW3,compound_phospatase_dataset 4
4,4,MAAKGLLVMDVDSTLIEEEVIDLLGEKAGMGDKISEITAAAMSGEI...,CC(C)(COP(=O)(O)OP(=O)(O)OC[C@H]1O[C@@H](n2cnc...,0,Q9CHW3,compound_phospatase_dataset 5
...,...,...,...,...,...,...
35965,35965,MYRVFVFDLDGTLLNDNLEISEKDRRNIEKLSRKCYVVFASGRMLV...,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=...,0,Q9WZB9,compound_phospatase_dataset 161
35966,35966,MYRVFVFDLDGTLLNDNLEISEKDRRNIEKLSRKCYVVFASGRMLV...,O=c1ccn([C@@H]2O[C@H](COP(=O)(O)O)[C@@H](O)[C@...,0,Q9WZB9,compound_phospatase_dataset 162
35967,35967,MYRVFVFDLDGTLLNDNLEISEKDRRNIEKLSRKCYVVFASGRMLV...,O=c1ccn([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O)[C@...,0,Q9WZB9,compound_phospatase_dataset 163
35968,35968,MYRVFVFDLDGTLLNDNLEISEKDRRNIEKLSRKCYVVFASGRMLV...,O=c1ccn([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)OP(=O...,0,Q9WZB9,compound_phospatase_dataset 164
35969,35969,MYRVFVFDLDGTLLNDNLEISEKDRRNIEKLSRKCYVVFASGRMLV...,O=c1ccn([C@H]2C[C@H](O)[C@@H](COP(=O)(O)O)O2)c...,0,Q9WZB9,compound_phospatase_dataset 165

In [7]:
phospatase.to_csv("phospatase_data.csv", index=False)

# Halogenase data

In [92]:
import pandas as pd


halogenase = pd.read_csv("halogenase_NaCl_binary.csv")
halogenase.columns = ["Index", "Sequence", "SMILES", "Binding"]
halogenase

,Index,Sequence,SMILES,Binding
0,0,MANQVPSTTRVLVIGGGPAGSYAACCLAREGVDVVVLEADKFPRYH...,C1(C2=C(CNCC2)N3)=C3C=CC=C1,0
1,1,MANQVPSTTRVLVIGGGPAGSYAACCLAREGVDVVVLEADKFPRYH...,C1(N2CCNCC2)=CC=CC=C1,0
2,2,MANQVPSTTRVLVIGGGPAGSYAACCLAREGVDVVVLEADKFPRYH...,CC(C)(C)C(C1=CC=C(N)C=C1)C2=CC=C(N)C=C2,0
3,3,MANQVPSTTRVLVIGGGPAGSYAACCLAREGVDVVVLEADKFPRYH...,CC(C)C(CCCN(C)CCC1=CC(OC)=C(OC)C=C1)(C#N)C2=CC...,0
4,4,MANQVPSTTRVLVIGGGPAGSYAACCLAREGVDVVVLEADKFPRYH...,CC(O1)(C)C=CC2=C1C=CC3=C2OC[C@@H](C4=C(O)C=C(O...,0
...,...,...,...,...
2599,2599,MYKIKKIMIVGGGTSGWMTAAALAKFLIPHGIDIELIESSAISSVG...,O[C@H](C[C@](OC1=C(OC)C=C2)3[H])C=C[C@]43C1=C2...,0
2600,2600,MYKIKKIMIVGGGTSGWMTAAALAKFLIPHGIDIELIESSAISSVG...,O[C@H]([C@@H]1C[C@H]2[C@H](C[N@@]1CC2)C=C)C3=C...,0
2601,2601,MYKIKKIMIVGGGTSGWMTAAALAKFLIPHGIDIELIESSAISSVG...,[H][C@@]1(NCCC2=C1C=C(OC)C(OC)=C2)C[C@@]3([H])...,0
2602,2602,MYKIKKIMIVGGGTSGWMTAAALAKFLIPHGIDIELIESSAISSVG...,[H][C@](N1CC2)(C[C@@](C(C(OC)=O)=CO[C@H]3C)([H...,0
2603,2603,MYKIKKIMIVGGGTSGWMTAAALAKFLIPHGIDIELIESSAISSVG...,[H][C@](N1CC2)(C[C@@]([C@@H](C(OC)=O)[C@@H](O)...,0

In [93]:
halogenase_sequences = pd.read_excel("halogenase_metadata/oc9b00835_si_005.xlsx")
halogenase_sequences = halogenase_sequences.loc[:, ["uniprot_updated", "sequence"]]
halogenase_sequences.columns = ["Enzyme ID", "Sequence"]

In [94]:
import numpy as np


halogenase = pd.merge(halogenase, halogenase_sequences, on="Sequence")
halogenase.columns = ["Index", "Sequence", "SMILES", "Binding", "Enzyme ID"]
# Check for None or NaN values
nan_mask = np.array([str(x).lower() == 'nan' for x in np.array(halogenase.loc[:, "Enzyme ID"])])

# Count the number of NaN values
nan_count = np.sum(nan_mask)
nan_count

0

In [95]:
halogenase

,Index,Sequence,SMILES,Binding,Enzyme ID
0,0,MANQVPSTTRVLVIGGGPAGSYAACCLAREGVDVVVLEADKFPRYH...,C1(C2=C(CNCC2)N3)=C3C=CC=C1,0,A0A0H2S825
1,1,MANQVPSTTRVLVIGGGPAGSYAACCLAREGVDVVVLEADKFPRYH...,C1(N2CCNCC2)=CC=CC=C1,0,A0A0H2S825
2,2,MANQVPSTTRVLVIGGGPAGSYAACCLAREGVDVVVLEADKFPRYH...,CC(C)(C)C(C1=CC=C(N)C=C1)C2=CC=C(N)C=C2,0,A0A0H2S825
3,3,MANQVPSTTRVLVIGGGPAGSYAACCLAREGVDVVVLEADKFPRYH...,CC(C)C(CCCN(C)CCC1=CC(OC)=C(OC)C=C1)(C#N)C2=CC...,0,A0A0H2S825
4,4,MANQVPSTTRVLVIGGGPAGSYAACCLAREGVDVVVLEADKFPRYH...,CC(O1)(C)C=CC2=C1C=CC3=C2OC[C@@H](C4=C(O)C=C(O...,0,A0A0H2S825
...,...,...,...,...,...
2599,2599,MYKIKKIMIVGGGTSGWMTAAALAKFLIPHGIDIELIESSAISSVG...,O[C@H](C[C@](OC1=C(OC)C=C2)3[H])C=C[C@]43C1=C2...,0,Q21LS3
2600,2600,MYKIKKIMIVGGGTSGWMTAAALAKFLIPHGIDIELIESSAISSVG...,O[C@H]([C@@H]1C[C@H]2[C@H](C[N@@]1CC2)C=C)C3=C...,0,Q21LS3
2601,2601,MYKIKKIMIVGGGTSGWMTAAALAKFLIPHGIDIELIESSAISSVG...,[H][C@@]1(NCCC2=C1C=C(OC)C(OC)=C2)C[C@@]3([H])...,0,Q21LS3
2602,2602,MYKIKKIMIVGGGTSGWMTAAALAKFLIPHGIDIELIESSAISSVG...,[H][C@](N1CC2)(C[C@@](C(C(OC)=O)=CO[C@H]3C)([H...,0,Q21LS3
2603,2603,MYKIKKIMIVGGGTSGWMTAAALAKFLIPHGIDIELIESSAISSVG...,[H][C@](N1CC2)(C[C@@]([C@@H](C(OC)=O)[C@@H](O)...,0,Q21LS3

In [96]:
halogenase = convert_dataset(halogenase, "halogenase_nacl")
halogenase.to_csv("halogenase_nacl_data.csv", index=False)

# Esterase

In [109]:
import pandas as pd


esterase = pd.read_csv("esterase_binary.csv")
esterase.columns = ["Index", "Sequence", "SMILES", "Binding"]
esterase

,Index,Sequence,SMILES,Binding
0,0,MLLPETRNLLDLMDAATRGGRPRLETLPHAVGRKAVDKMSEDGEAD...,CC(=O)OC1=CC=CC2=CC=CC=C21,1.0
1,1,MGLQKLIVRTLMKLPESWILKLAGGTPVEIDGRTMDPRIQLLAAQG...,CC(=O)OC1=CC=CC2=CC=CC=C21,1.0
2,2,MPDTTSLNIADDVRMDPRLKAMLAAFPMMEQQTFQTREEQVANANT...,CC(=O)OC1=CC=CC2=CC=CC=C21,1.0
3,3,MALPSGSDPAFSQPKSVLDAGLTCQGASPSSVSKPILLVPGTGTTG...,CC(=O)OC1=CC=CC2=CC=CC=C21,1.0
4,4,MSLQRMIVRTLLKLPDGLLVKMSGGKPLEIDGRTLDARVQLLASQG...,CC(=O)OC1=CC=CC2=CC=CC=C21,1.0
...,...,...,...,...
14011,14011,MFGGEIIMLRTGTRFAVALTAVALALGPVSTGQAQTARKPAASKAA...,CCCCCCCCCCCC(=O)OCC(COC(=O)CCCCCCCCCCC)OC(=O)C...,0.0
14012,14012,MCATHKAFFSYVWRKFLNMYRFSVISSFLALSCFLSLASYELPDHS...,CCCCCCCCCCCC(=O)OCC(COC(=O)CCCCCCCCCCC)OC(=O)C...,0.0
14013,14013,MRKHLRSFSFILLSLFFVAFPMSAFSEASPAEALAEAQKQHDEWGF...,CCCCCCCCCCCC(=O)OCC(COC(=O)CCCCCCCCCCC)OC(=O)C...,0.0
14014,14014,MKHLFVLSLFISCFFITHAQEHTEQPIRPDAVFMGNSITQNWRNFH...,CCCCCCCCCCCC(=O)OCC(COC(=O)CCCCCCCCCCC)OC(=O)C...,0.0
14015,14015,MKKTALKFCIFAIALTVSVLGASLAFSADTSCKTKYPIILAHGMGF...,CCCCCCCCCCCC(=O)OCC(COC(=O)CCCCCCCCCCC)OC(=O)C...,0.0

In [110]:
esterase_sequences = pd.read_excel("esterase_metadata/cb7b00996_si_002.xls")
esterase_sequences = esterase_sequences.loc[:, ["Accesion number", "AMINO ACID SEQUENCE"]]
esterase_sequences.columns = ["Enzyme ID", "Sequence"]

In [111]:
import numpy as np


esterase = pd.merge(esterase, esterase_sequences, on="Sequence")
esterase.columns = ["Index", "Sequence", "SMILES", "Binding", "Enzyme ID"]
# Check for None or NaN values
nan_mask = np.array([str(x).lower() == 'nan' for x in np.array(esterase.loc[:, "Enzyme ID"])])

# Count the number of NaN values
nan_count = np.sum(nan_mask)
nan_count

0

In [112]:
esterase

,Index,Sequence,SMILES,Binding,Enzyme ID
0,0,MLLPETRNLLDLMDAATRGGRPRLETLPHAVGRKAVDKMSEDGEAD...,CC(=O)OC1=CC=CC2=CC=CC=C21,1.0,SRA059294
1,146,MLLPETRNLLDLMDAATRGGRPRLETLPHAVGRKAVDKMSEDGEAD...,CCCC(=O)OC1=CC=CC2=CC=CC=C21,1.0,SRA059294
2,292,MLLPETRNLLDLMDAATRGGRPRLETLPHAVGRKAVDKMSEDGEAD...,CC(=O)OCC(COC(=O)C)OC(=O)C,1.0,SRA059294
3,438,MLLPETRNLLDLMDAATRGGRPRLETLPHAVGRKAVDKMSEDGEAD...,CCC(=O)OCC(COC(=O)CC)OC(=O)CC,1.0,SRA059294
4,584,MLLPETRNLLDLMDAATRGGRPRLETLPHAVGRKAVDKMSEDGEAD...,CCCC(=O)OCC(COC(=O)CCC)OC(=O)CCC,1.0,SRA059294
...,...,...,...,...,...
12283,13431,MKKTALKFCIFAIALTVSVLGASLAFSADTSCKTKYPIILAHGMGF...,CCCCOC(=O)C,0.0,KP347726
12284,13577,MKKTALKFCIFAIALTVSVLGASLAFSADTSCKTKYPIILAHGMGF...,CC(=O)OC1=CC=CC=C1,0.0,KP347726
12285,13723,MKKTALKFCIFAIALTVSVLGASLAFSADTSCKTKYPIILAHGMGF...,CCC(=O)OC1=CC=CC=C1,0.0,KP347726
12286,13869,MKKTALKFCIFAIALTVSVLGASLAFSADTSCKTKYPIILAHGMGF...,CC(=O)OCC(C(C(C(C=O)OC(=O)C)OC(=O)C)OC(=O)C)OC...,0.0,KP347726
12287,14015,MKKTALKFCIFAIALTVSVLGASLAFSADTSCKTKYPIILAHGMGF...,CCCCCCCCCCCC(=O)OCC(COC(=O)CCCCCCCCCCC)OC(=O)C...,0.0,KP347726

In [113]:
esterase = convert_dataset(esterase, "esterase")
esterase.to_csv("esterase_data.csv", index=False)

# DUF

In [122]:
import pandas as pd


duf = pd.read_csv("duf_binary.csv")
duf.columns = ["Index", "Sequence", "SMILES", "Binding"]
duf

,Index,Sequence,SMILES,Binding
0,0,AGVYLKACINGARTPDQHPRLPVTPDQLAAEAVAAHRAGASAVHMH...,OC(CC(/C=C/C)=O)=O,0
1,1,AGVYLKACINGARTPDQHPRLPVTPDQLAAEAVAAHRAGASAVHMH...,OC(CC(C(C)C)=O)=O,0
2,2,AGVYLKACINGARTPDQHPRLPVTPDQLAAEAVAAHRAGASAVHMH...,OC(CC(C1=C(NC=O)C=CC=C1)=O)=O,0
3,3,AGVYLKACINGARTPDQHPRLPVTPDQLAAEAVAAHRAGASAVHMH...,OC(CC(C1=CC=C(O)C=C1)=O)=O,0
4,4,AGVYLKACINGARTPDQHPRLPVTPDQLAAEAVAAHRAGASAVHMH...,OC(CC(C1=CC=CC=C1)=O)=O,0
...,...,...,...,...
2732,2732,VLPRIMLAPTGARLTKADHPALPVTIPEIVAAARAGRAAGADGLHA...,OC(CC(CCCCCCC)=O)=O,0
2733,2733,VLPRIMLAPTGARLTKADHPALPVTIPEIVAAARAGRAAGADGLHA...,OC(CC(CCCCCCCCC)=O)=O,0
2734,2734,VLPRIMLAPTGARLTKADHPALPVTIPEIVAAARAGRAAGADGLHA...,OC(CC(CCCNC(C)=O)=O)=O,0
2735,2735,VLPRIMLAPTGARLTKADHPALPVTIPEIVAAARAGRAAGADGLHA...,OC(CC(C[C@@H](N)C)=O)=O,0
2736,2736,VLPRIMLAPTGARLTKADHPALPVTIPEIVAAARAGRAAGADGLHA...,OC(CC(C[N+](C)(C)C)=O)=O,0

In [123]:
from itertools import groupby
from typing import Iterable, Tuple


def fasta_iter(fasta_name: str) -> Iterable[Tuple[str, str]]:
    """fasta_iter.

     modified from Brent Pedersen
     Correct Way To Parse A Fasta File In Python
     given a fasta file. yield tuples of header, sequence

    Args:
        fasta_name (str): fasta_name

    Returns:
        Iterable[tuple] of (headerStr, seq)
    """
    # open fasta file
    fh = open(fasta_name)

    # ditch the boolean (x[0]) and just keep the header or sequence since
    # we know they alternate.
    faiter = (x[1] for x in groupby(fh, lambda line: line[0] == ">"))

    for header in faiter:
        # drop the ">"
        headerStr = header.__next__()[1:].strip()

        # join all sequence lines to one.
        seq = "".join(s.strip() for s in faiter.__next__())

        yield (headerStr, seq)

seq_mapping = {
        seq.replace("-", ""): name.replace("BKACE", "KCE")
        for name, seq in fasta_iter("duf_metadata/duf_msa.txt")
    }

In [125]:
sequences_ids = []

for i, row in duf.iterrows():
    sequence = row["Sequence"]
    sequences_ids.append(seq_mapping[sequence])
duf["Enzyme ID"] = sequences_ids
duf

,Index,Sequence,SMILES,Binding,Enzyme ID
0,0,AGVYLKACINGARTPDQHPRLPVTPDQLAAEAVAAHRAGASAVHMH...,OC(CC(/C=C/C)=O)=O,0,KCE25
1,1,AGVYLKACINGARTPDQHPRLPVTPDQLAAEAVAAHRAGASAVHMH...,OC(CC(C(C)C)=O)=O,0,KCE25
2,2,AGVYLKACINGARTPDQHPRLPVTPDQLAAEAVAAHRAGASAVHMH...,OC(CC(C1=C(NC=O)C=CC=C1)=O)=O,0,KCE25
3,3,AGVYLKACINGARTPDQHPRLPVTPDQLAAEAVAAHRAGASAVHMH...,OC(CC(C1=CC=C(O)C=C1)=O)=O,0,KCE25
4,4,AGVYLKACINGARTPDQHPRLPVTPDQLAAEAVAAHRAGASAVHMH...,OC(CC(C1=CC=CC=C1)=O)=O,0,KCE25
...,...,...,...,...,...
2732,2732,VLPRIMLAPTGARLTKADHPALPVTIPEIVAAARAGRAAGADGLHA...,OC(CC(CCCCCCC)=O)=O,0,KCE449
2733,2733,VLPRIMLAPTGARLTKADHPALPVTIPEIVAAARAGRAAGADGLHA...,OC(CC(CCCCCCCCC)=O)=O,0,KCE449
2734,2734,VLPRIMLAPTGARLTKADHPALPVTIPEIVAAARAGRAAGADGLHA...,OC(CC(CCCNC(C)=O)=O)=O,0,KCE449
2735,2735,VLPRIMLAPTGARLTKADHPALPVTIPEIVAAARAGRAAGADGLHA...,OC(CC(C[C@@H](N)C)=O)=O,0,KCE449
2736,2736,VLPRIMLAPTGARLTKADHPALPVTIPEIVAAARAGRAAGADGLHA...,OC(CC(C[N+](C)(C)C)=O)=O,0,KCE449

In [126]:
duf = convert_dataset(duf, "duf")
duf.to_csv("duf_data.csv", index=False)

# Amino-transferase

In [143]:
import pandas as pd


amino_transferase = pd.read_csv("aminotransferase_binary.csv")
amino_transferase.columns = ["Index", "Sequence", "SMILES", "Binding"]
amino_transferase

,Index,Sequence,SMILES,Binding
0,0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0
1,1,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C[C@@H](C(=O)O)N,1
2,2,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)[C@@H](C(=O)O)N,0
3,3,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)C[C@@H](C(=O)O)N,1
4,4,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC[C@H](C)[C@@H](C(=O)O)N,0
...,...,...,...,...
445,445,MAEENGMIWMNGKIVPWEQATTHVLSHSLHYGLAVFEGMRAYKTDN...,C(CC(=O)N)[C@@H](C(=O)O)N,1
446,446,MAEENGMIWMNGKIVPWEQATTHVLSHSLHYGLAVFEGMRAYKTDN...,C([C@@H](C(=O)O)N)C(=O)O,1
447,447,MAEENGMIWMNGKIVPWEQATTHVLSHSLHYGLAVFEGMRAYKTDN...,C(CCN)C[C@@H](C(=O)O)N,0
448,448,MAEENGMIWMNGKIVPWEQATTHVLSHSLHYGLAVFEGMRAYKTDN...,C(C[C@@H](C(=O)O)N)CN=C(N)N,0
449,449,MAEENGMIWMNGKIVPWEQATTHVLSHSLHYGLAVFEGMRAYKTDN...,C1=C(NC=N1)C[C@@H](C(=O)O)N,1

In [144]:
import pandas as pd

amino_transferase_sequences = pd.read_csv("aminotransferase_metadata/aminotransferase_sequence_file.txt", sep="\t")
amino_transferase_sequences = amino_transferase_sequences.loc[:, ["Entry", "Sequence"]]

In [145]:
import numpy as np


amino_transferase = pd.merge(amino_transferase, amino_transferase_sequences, on="Sequence")
amino_transferase.columns = ["Index", "Sequence", "SMILES", "Binding", "Enzyme ID"]
# Check for None or NaN values
nan_mask = np.array([str(x).lower() == 'nan' for x in np.array(amino_transferase.loc[:, "Enzyme ID"])])

# Count the number of NaN values
nan_count = np.sum(nan_mask)
nan_count

0

In [146]:
amino_transferase

,Index,Sequence,SMILES,Binding,Enzyme ID
0,0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0,P00509
1,1,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C[C@@H](C(=O)O)N,1,P00509
2,2,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)[C@@H](C(=O)O)N,0,P00509
3,3,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)C[C@@H](C(=O)O)N,1,P00509
4,4,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC[C@H](C)[C@@H](C(=O)O)N,0,P00509
...,...,...,...,...,...
445,445,MAEENGMIWMNGKIVPWEQATTHVLSHSLHYGLAVFEGMRAYKTDN...,C(CC(=O)N)[C@@H](C(=O)O)N,1,A0A2E1TNK5
446,446,MAEENGMIWMNGKIVPWEQATTHVLSHSLHYGLAVFEGMRAYKTDN...,C([C@@H](C(=O)O)N)C(=O)O,1,A0A2E1TNK5
447,447,MAEENGMIWMNGKIVPWEQATTHVLSHSLHYGLAVFEGMRAYKTDN...,C(CCN)C[C@@H](C(=O)O)N,0,A0A2E1TNK5
448,448,MAEENGMIWMNGKIVPWEQATTHVLSHSLHYGLAVFEGMRAYKTDN...,C(C[C@@H](C(=O)O)N)CN=C(N)N,0,A0A2E1TNK5
449,449,MAEENGMIWMNGKIVPWEQATTHVLSHSLHYGLAVFEGMRAYKTDN...,C1=C(NC=N1)C[C@@H](C(=O)O)N,1,A0A2E1TNK5

In [147]:
amino_transferase = convert_dataset(amino_transferase, "aminotransferase")
amino_transferase.to_csv("aminotransferase_data.csv", index=False)

# Nitrilase

In [132]:
import pandas as pd


nitrilase = pd.read_csv("nitrilase_binary.csv")
nitrilase.columns = ["Index", "Sequence", "SMILES", "Binding"]

In [134]:
import pandas as pd

nitrilase_sequences = pd.read_csv("nitrilase_metadata/nitrilases_data.tsv", sep="\t")
nitrilase_sequences = nitrilase_sequences.loc[:, ["Entry", "Sequence"]]
nitrilase_sequences

     Entry                                           Sequence
0   P20960  MQTRKIVRAAAVQAASPNYDLATGVDKTIELARQARDEGCDLIVFG...
1   B4AL96  MEVFNMTSIYPKFRAAAVQAAPIYLNLEATVQKSCELIDEAASNGA...
2   Q89GE3  MQDTKFKVAVVQAAPVFMDAPASVAKAIGFIAEAGAAGAKLLAFPE...
3   A5EKU8  MGLAHPKYKVAVVQAAPAWLDLDASIKKTIALIEEAADKGAKLIAF...
4   Q2GR86  MSAKLTKFKVAAAHAAPVFMNKAATTKKAIRLIEEAGAAAVKVLVF...
5   Q6N284  MAKLKVAAVQATTVPFDAAAATVRTVALIGEAAAKGAKIAVFPEAF...
6   A0LKP2  MKTDLRVAVVQAGAIPFDVEGSVEKACSLLADAAAKGAELAVFPEA...
7   A5ETE9  MSNDRSFTAAMVQMRTALLPEPSLEQGTRLIREAVAQGAEYVQTPE...
8   Q2J474  MTETAPFNAALVQMRTGLLPGPSLEQGTKLIREAAAAGADYVLTPE...
9   Q5LLB2  MLPLQDFPKFTAAAVQASPVFLDAHKTAQKAVDLIAEAAGNGAELV...
10  E3HN55  MSMQQSFKAAVIQAASIPTDSIACAEKAASLIRQAAEQGARVLVFP...
11  F0Q9Y1  MLELPKFKAAAVQAAPVFLDTDATVDKVCRLIAEAAGNGAQLVAFP...
12  G8CXY5  MQTRKIVRAAAVQAASPNYDLATGVDKTIELARQARDEGCDLIVFG...
13  Q819F0  MKVACIQMDIVFGDVEKNIENAKNKISEAMKERPDVIVLPELWTTG...
14  A5MYU1  MLNYYRSDIMAKNSIKSVRVAAVQTSPVIMNLDDTVEKTLTLIKKA...
15  C5DH06  MMAKKVVAALQVGTSPGGTQETLEKILSYEKEIIEAGAKLIVIPEA...
16  D1C8L7  MCWCYPGCKWGGPQFRSRKRAALSRPTVRRWAMSTVRAAVVQAAPV...
17  A7TP07  MSSILSQKLKVALIQLAGSKPDKSANLQRAAKFIEKALIDQPDTKI...

In [135]:
import numpy as np


nitrilase = pd.merge(nitrilase, nitrilase_sequences, on="Sequence")
nitrilase.columns = ["Index", "Sequence", "SMILES", "Binding", "Enzyme ID"]

# Check for None or NaN values
nan_mask = np.array([str(x).lower() == 'nan' for x in np.array(nitrilase.loc[:, "Enzyme ID"])])

# Count the number of NaN values
nan_count = np.sum(nan_mask)
nan_count

0

In [136]:
nitrilase

,Index,Sequence,SMILES,Binding,Enzyme ID
0,0,MQDTKFKVAVVQAAPVFMDAPASVAKAIGFIAEAGAAGAKLLAFPE...,CC#N,0,Q89GE3
1,18,MQDTKFKVAVVQAAPVFMDAPASVAKAIGFIAEAGAAGAKLLAFPE...,CCC#N,0,Q89GE3
2,36,MQDTKFKVAVVQAAPVFMDAPASVAKAIGFIAEAGAAGAKLLAFPE...,CCCC#N,0,Q89GE3
3,54,MQDTKFKVAVVQAAPVFMDAPASVAKAIGFIAEAGAAGAKLLAFPE...,CCCCC#N,0,Q89GE3
4,72,MQDTKFKVAVVQAAPVFMDAPASVAKAIGFIAEAGAAGAKLLAFPE...,CCCCCC#N,1,Q89GE3
...,...,...,...,...,...
679,611,MEVFNMTSIYPKFRAAAVQAAPIYLNLEATVQKSCELIDEAASNGA...,OC(C1=CC=CC=C1)C#N,1,B4AL96
680,629,MEVFNMTSIYPKFRAAAVQAAPIYLNLEATVQKSCELIDEAASNGA...,CC(C1=CC=C(CC(C)C)C=C1)C#N,0,B4AL96
681,647,MEVFNMTSIYPKFRAAAVQAAPIYLNLEATVQKSCELIDEAASNGA...,N#CC(C1=CC=CC=C1)C2=CC=CC=C2,0,B4AL96
682,665,MEVFNMTSIYPKFRAAAVQAAPIYLNLEATVQKSCELIDEAASNGA...,N#CCC1=CC=C2C=CC=CC2=C1,1,B4AL96
683,683,MEVFNMTSIYPKFRAAAVQAAPIYLNLEATVQKSCELIDEAASNGA...,N#CCCC1=CC=CC=C1,0,B4AL96

In [137]:
nitrilase = convert_dataset(nitrilase, "nitrilase")
nitrilase.to_csv("nitrilase_data.csv", index=False)

# OLea

In [18]:
import pandas as pd


phospatase = pd.read_csv("olea_binary.csv")
phospatase.columns = ["Index", "Sequence", "SMILES", "Binding"]
phospatase = convert_dataset(phospatase, "olea")
phospatase.to_csv("olea_data.csv", index=False)

# Merge data

In [8]:
aminotransferase = pd.read_csv("aminotransferase_data.csv")
aminotransferase["Publication"] = ["https://pubs.acs.org/doi/10.1021/acscatal.0c01895"] * aminotransferase.shape[0]
phospatase = pd.read_csv("phospatase_data.csv")
phospatase["Publication"] = ["https://doi.org/10.1073/pnas.1423570112"] * phospatase.shape[0]
halogenase_nacl = pd.read_csv("halogenase_nacl_data.csv")
halogenase_nacl["Publication"] = ["10.1021/acscentsci.9b00835"] * halogenase_nacl.shape[0]
halogenase_nabr = pd.read_csv("halogenase_nabr_data.csv")
halogenase_nabr["Publication"] = ["10.1021/acscentsci.9b00835"] * halogenase_nabr.shape[0]
# olea = pd.read_csv("olea_data.csv")
nitrilase = pd.read_csv("nitrilase_data.csv")
nitrilase["Publication"] = ["10.1039/c4cc06021k"] * nitrilase.shape[0]
duf = pd.read_csv("duf_data.csv")
duf["Publication"] = ["https://doi.org/10.1038/nchembio.1387"] * duf.shape[0]
esterase = pd.read_csv("esterase_data.csv")
esterase["Publication"] = ["10.1021/acschembio.7b00996"] * esterase.shape[0]

In [9]:
merged_dataset = pd.concat([aminotransferase, phospatase, halogenase_nacl, nitrilase, duf, esterase], axis = 0)
merged_dataset

,Index,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication
0,0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
1,1,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 2,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
2,2,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 3,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
3,3,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 4,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
4,4,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC[C@H](C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 5,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
...,...,...,...,...,...,...,...
12283,13431,MKKTALKFCIFAIALTVSVLGASLAFSADTSCKTKYPIILAHGMGF...,CCCCOC(=O)C,0.0,KP347726,compound_esterase_dataset 92,10.1021/acschembio.7b00996
12284,13577,MKKTALKFCIFAIALTVSVLGASLAFSADTSCKTKYPIILAHGMGF...,CC(=O)OC1=CC=CC=C1,0.0,KP347726,compound_esterase_dataset 93,10.1021/acschembio.7b00996
12285,13723,MKKTALKFCIFAIALTVSVLGASLAFSADTSCKTKYPIILAHGMGF...,CCC(=O)OC1=CC=CC=C1,0.0,KP347726,compound_esterase_dataset 94,10.1021/acschembio.7b00996
12286,13869,MKKTALKFCIFAIALTVSVLGASLAFSADTSCKTKYPIILAHGMGF...,CC(=O)OCC(C(C(C(C=O)OC(=O)C)OC(=O)C)OC(=O)C)OC...,0.0,KP347726,compound_esterase_dataset 95,10.1021/acschembio.7b00996
12287,14015,MKKTALKFCIFAIALTVSVLGASLAFSADTSCKTKYPIILAHGMGF...,CCCCCCCCCCCC(=O)OCC(COC(=O)CCCCCCCCCCC)OC(=O)C...,0.0,KP347726,compound_esterase_dataset 96,10.1021/acschembio.7b00996

In [10]:
merged_dataset.to_csv("goldman_data.csv", index=False)