In [4]:
import pandas as pd


dataset = pd.read_csv("curated_dataset_no_stereochemistry_duplicates.csv")
dataset

,Unnamed: 0,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,Validated,RHEA_ID,EC number,reaction_SMILES
0,0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
1,1,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 2,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
2,2,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 3,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
3,3,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 4,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
4,4,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC[C@H](C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 5,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
52131,76466,MKYRAVTLESFGYQLAPVVVSTSDLEARLEPLYRQLRIAPGQLQAM...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Pelobacter_propionicus,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
52132,76467,MAFLSVNNVEIVGLAAAVPKNVETLDNLEFFAPGEAEKVMALTGIK...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Bacteroides_luti,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
52133,76468,MSAPRYSQVSAVAVRLPDEDLTTPELEELLAERNPRVDVPRGLIER...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Nonomuraea_candida,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
52134,76469,MRYQRVFINKIAYELPKEKVATSFLEEQLTDVYQELGIPLGQVEAL...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Legionella_brunensis,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
52135,76470,MTYSRIGQIAVHLPEGGRTSAEVEALVAELNPGFEPPEGLIERFTG...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Allokutzneria_albata,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN

In [16]:
from plants_sm.io.pickle import read_pickle

splits = read_pickle("splits_0_8_proteins_train_val_test.pkl")

In [20]:
set(splits[0][0])

{'Q9KLY5',
 'Q94515',
 'P0AFC7',
 'P0A870',
 'Q6B516',
 'Q9FIA0',
 'Q9GTV1',
 'A0A1D8PPA8',
 'P14925',
 'G0XYG8',
 'Q9HCL2',
 'P38584',
 'Q5QXU4',
 'Q61425',
 'Q02053',
 'Q9LW26',
 'P00490',
 'P27008',
 'Q6FV03',
 'Q03778',
 'Q86UL3',
 'O06836',
 'P79023',
 'Q54XE5',
 'Q59WT3',
 'P11076',
 'Q9U912',
 'P63224',
 'P05201',
 'P47095',
 'Q9USP8',
 'P48360',
 'Q9W3Z3',
 'Q921A4',
 'Q7F1K9',
 'P60763',
 'Q64689',
 'P33121',
 'Q76L34',
 'O75164',
 'Q02394',
 'O35952',
 'Q10075',
 'O94446',
 'Q0WP12',
 'Q8L799',
 'P05982',
 'Q99M04',
 'P62601',
 'P55345',
 'P0A6E1',
 'P0A722',
 'Q9QYT7',
 'P42207',
 'Q9D5J6',
 'Q8JZL3',
 'P16118',
 'P9WND1',
 'Q7G192',
 'Q9VYD1',
 'Q02846',
 'Q9FJ95',
 'P25522',
 'P15259',
 'Q64J17',
 'Q9PU40',
 'P75876',
 'Q96EQ9',
 'Q63321',
 'Q9SQ67',
 'P50213',
 'P42951',
 'Q9NY97',
 'P00944',
 'P9WKI3',
 'O80852',
 'O60105',
 'Q6NMK1',
 'F4J849',
 'A4YGN2',
 'Q64442',
 'Q8PUQ3',
 'P07099',
 'Q5AF03',
 'O00154',
 'Q9H9P8',
 'Q02337',
 'P37440',
 'Q62639',
 'F8UL80',
 'Q8IUC8',
 'Q9EX06',
 'Q9I491',
 'J3QMK6',
 'Q9V3U0',
 'P0A6W0',
 'E9QYP0',
 'Q03786',
 'Q22067',
 'P32264',
 'Q5SM16',
 'P0AFD1',
 'Q24205',
 'Q2UP46',
 'P97224',
 'O80574',
 'P20577',
 'H9BFW7',
 'P9WKK7',
 'O75342',
 'Q5A7Q2',
 'Q9XXK6',
 'O95498',
 'P09139',
 'Q9UY84',
 'P0AC38',
 'P54318',
 'B2J4A4',
 'Q9X0X3',
 'Q15286',
 'A9CQL8',
 'Q2J474',
 'P0A8Q0',
 'Q9SLG9',
 'O74885',
 'Q9ZUH4',
 'Q47PS3',
 'D7URM0',
 'Q8W1W9',
 'Q9HXT9',
 'F1QWF7',
 'P70531',
 'Isoptericola_variabilis',
 'F4JPA9',
 'Q6FM56',
 'P46011',
 'Q47316',
 'P28903',
 'G0XYH7',
 'Q5NAI7',
 'P37649',
 'Q9GRG7',
 'Q8GW72',
 'O64238',
 'P52034',
 'P32179',
 'Q09768',
 'A3R052',
 'P0A873',
 'Q3LXA3',
 'Q9CAQ2',
 'P58710',
 'Q8JGL9',
 'P13864',
 'F4JQ95',
 'P39199',
 'Q60935',
 'P41247',
 'Q29460',
 'WP_015006593',
 'P16549',
 'D7URV0',
 'Q57V01',
 'P49017',
 'Q764T8',
 'D3XD61',
 'Q9UPS6',
 'Q9LFW1',
 'Humibacillus_sp.',
 'P33667',
 'Q8IRJ9',
 'O43272',
 'P31129',
 'Q9Y7U9',
 'Q9SB60',
 'D3ZW08',
 'P75691',
 'P0AG40',
 'P52643',
 'O70250',
 'P0AG20',
 'Q28007',
 'A5LSE1',
 'Q5HNV1',
 'KY483649',
 'P21146',
 'F4KHU8',
 'P9WH11',
 'Q9UBN7',
 'Q9HV49',
 'P41814',
 'Q9V3F2',
 'Q2G7X9',
 'P00966',
 'Q8I136',
 'P20594',
 'P35497',
 'Q8LDN8',
 'Q04089',
 'Q4WGM0',
 'Q21376',
 'Q9SKK4',
 'P25688',
 'O88876',
 'Q96WT2',
 'Q4QEG9',
 'Q15031',
 'Q8BQ86',
 'P77757',
 'Q91WG0',
 'P41759',
 'P32939',
 'Q5ABG1',
 'Q91VA0',
 'Q9S4D5',
 'P54071',
 'A0A384JAD8',
 'P35340',
 'Q8GI16',
 'P0CF36',
 'Q9SXS7',
 'Q9STG9',
 'P32582',
 'A9CES4',
 'Q16S21',
 'Q9UI43',
 'Q63342',
 'Q9WZC2',
 'Q9VF51',
 'Q9ZPI1',
 'Q9XHG1',
 'Q9SPN1',
 'Q08558',
 'Q8H2B4',
 'O77475',
 'Q12051',
 'A0A359KP67',
 'P18163',
 'KP347713',
 'O04998',
 'O88618',
 'Q8WQD8',
 'Q6DJR8',
 'Q9UJ70',
 'Q9AQI0',
 'D4ADS4',
 'P97325',
 'Q3U2J5',
 'Q88LM3',
 'Q9S9N9',
 'KCE54',
 'Q8N5Z0',
 'P75823',
 'A4VJB4',
 'P42337',
 'P19358',
 'P06988',
 'Q15126',
 'I1HY48',
 'Q969I3',
 'A2BIR0',
 'P09832',
 'Q9SUR6',
 'Q9P0J0',
 'P78356',
 'Q9GV45',
 'Q9RWE0',
 'Q54EX6',
 'Q9HU77',
 'P9WM13',
 'Q8BH00',
 'Q86SR1',
 'Q9FMP3',
 'F4I4A6',
 'Q8VWJ6',
 'P92994',
 'Q04462',
 'P08684',
 'UGT88A1',
 'P9WN01',
 'Q9LVZ7',
 'Q551V8',
 'Q93Y07',
 'KF801579',
 'Q93YU6',
 'P76423',
 'Q13093',
 'Q8W471',
 'Q38FH2',
 'Q58673',
 'O96838',
 'Q13572',
 'P06132',
 'Q50754',
 'Q7Z7W6',
 'Q8ZPX9',
 'Q6P7B9',
 'P24752',
 'P34947',
 'P18669',
 'P83944',
 'Q2QLV9',
 'P17892',
 'P20445',
 'Q9ZQ94',
 'Q8N0X4',
 'Q9JI99',
 'G8B7T4',
 'F4J6V6',
 'P46953',
 'UGT71B5',
 'Q9BYG0',
 'Q9R0N0',
 'Q8KQL2',
 'P16331',
 'C1IC55',
 'Q6A1A4',
 'O31612',
 'Q03262',
 'P10503',
 'Q1EC69',
 'P25605',
 'Q5W9E3',
 'Q81IN0',
 'KCE417',
 'U3LVZ7',
 'P14407',
 'Q8NHM5',
 'P0AEW4',
 'Q08499',
 'Q819K1',
 'Q8R4G6',
 'Q61194',
 'Q9HAW7',
 'O52762',
 'G9M9M3',
 'C2JBT4',
 'Q9BRR6',
 'C0H4R1',
 'K9NJ94',
 'Q9LDR4',
 'Q27Z07',
 'P08461',
 'P9WPQ5',
 'P38122',
 'P45975',
 'P0AFS3',
 'P31317',
 'P20576',
 'Q9SUC0',
 'P77302',
 'Q9JMK0',
 'P55249',
 'A2BFP6',
 'P49589',
 'Q8K3A2',
 'A0A6L8PK77',
 'Q9SJL8',
 'Q94252',
 'Q552R4',
 'P93155',
 'P05062',
 'Q8IDM2',
 'O60052',
 'Q8BVM4',
 'Q9VEP8',
 'B8ZV93',
 'Q9EPA7',
 'P47013',
 'Q08J23',
 'O49434',
 'F1QAF6',
 'Q93063',
 'P33225',
 'O02740',
 'Q9S7G6',
 'KY483647',
 'Q9KWR7',
 'Q0PCF4',
 'O88587',
 'O74928',
 'Q8CFC4',
 'Q680I5',
 'A0A0G2K2S1',
 'Q9VEJ0',
 'Q9VUF8',
 'P14779',
 'Q980R9',
 'Q8GSJ1',
 'P41250',
 'Q46505',
 'Q8VC97',
 'Q55E23',
 'A2CG09',
 'A0A060WKC7',
 'Q6UPE0',
 'Q9C6B3',
 'A8CDT3',
 'Q9BVS5',
 'Q9NIW2',
 'Q9FY99',
 'P09436',
 'UGT73B5',
 'P16617',
 'P52697',
 'O01653',
 'O05265',
 'P45416',
 'A0A120HUS7',
 'P09151',
 'G3X982',
 'Q03206',
 'Q4VCM1',
 'Q6P6C2',
 'C8VUF6',
 'Q9Y5K3',
 'Q8IKD3',
 'O80472',
 'P52074',
 'Q9R111',
 'A4VFY4',
 'Q9I297',
 'D3ZUA0',
 'Q9NQX3',
 'G5EBV0',
 'O60658',
 'P74840',
 'Q4QTJ2',
 'D5E0A1',
 'P71447',
 'A8P2G9',
 'Q9STS1',
 'Q8MK44',
 'Q08965',
 'A8WCU5',
 'O07427',
 'B9DH52',
 'Q6DWK3',
 'Q38E55',
 'P14081',
 'Q8AY29',
 'Q7T2P9',
 'Q17577',
 'Q48EB9',
 'Q9BPW9',
 'P9WNP7',
 'Q9M1I6',
 'Q8DP63',
 'P36551',
 'T2G6Z9',
 'Q9Z110',
 'Q10S82',
 'D2Z028',
 'P40881',
 'P09972',
 'P0A8N5',
 'P15496',
 'P35354',
 'Q6T707',
 'Q1JPY5',
 'Q96GW9',
 'P41227',
 'KCE511',
 'Q01341',
 'Q8CGV2',
 'Q6AY99',
 'C6KT66',
 'B7UI22',
 'P95482',
 'C8V494',
 'Q9W3J5',
 'B1V8J4',
 'Q02353',
 'P03763',
 'Q8IVS2',
 'P12998',
 'Q15274',
 'P9WGT1',
 'P76518',
 'A0A0T7AQA7',
 'P05042',
 'Q9SE93',
 'O49299',
 'Q5XPT3',
 'O35263',
 'P45513',
 'P9WNS5',
 'Q99JY0',
 'P25519',
 'Q59WC5',
 'P31254',
 'A0A314KSQ4',
 'Q8NCH0',
 'B5SRV2',
 'Q46939',
 'O42842',
 'Q8TFN1',
 'P32719',
 'P32474',
 'Q9Y5X9',
 'P75782',
 'Q9W1V6',
 'Q9LW20',
 'O25103',
 'Q9H6R3',
 'O97193',
 'P71864',
 'P0A836',
 'P0DI07',
 'Q8XX94',
 'Q9ZUY3',
 'F4JVY8',
 'C0JXB7',
 'P45376',
 'D3XD87',
 'P9WQ29',
 'O58389',
 'Q599M3',
 'G5EB59',
 'P60390',
 'P00459',
 'Q8MS59',
 'P28748',
 'Q9SGU9',
 'P0A9S1',
 'D4AC20',
 'Q9N0F3',
 'Q8CHS7',
 'Q8IKP7',
 'Q9VM15',
 'Q8TC12',
 'P56937',
 'P08157',
 'O75478',
 'Q9CXA2',
 'Q9Y8C1',
 'Q96NR8',
 'Q0IMS9',
 'Q93NG3',
 'O53493',
 'P42336',
 'O14026',
 'Q8LG77',
 'P32377',
 'P08037',
 'P27657',
 'Q8I5T2',
 'Q9FNP9',
 'P05459',
 'Q9Y0Z0',
 'P55809',
 'Q8N371',
 'P18886',
 'Q7U4Z9',
 'P25342',
 'P08204',
 'Q54I79',
 'P0CB22',
 'KP347734',
 'P0A8N3',
 'Q8C196',
 'Q08295',
 'Q38EV2',
 'Q8MZM3',
 'P0ABF8',
 'O08395',
 'Q2F5L3',
 'Q9GZT9',
 'O23181',
 'Q6RYT0',
 'P9WKA7',
 'Q02401',
 'P27882',
 'P0AC84',
 'Q4GZ26',
 'D6XEJ9',
 'P39829',
 'O80689',
 'Q01063',
 'KCE238',
 'Q9SJD4',
 'Q1JUQ0',
 'Q9Z0J4',
 'Q9W4N2',
 'P9WJJ3',
 'Q8S9F2',
 'Q6FMJ4',
 'Q922Z0',
 'Q9FJI5',
 'P9WPJ7',
 'Q9FMD9',
 'P09368',
 'Q9HZ23',
 'P52895',
 'Q9JJF3',
 'Q7JWF1',
 'P70752',
 'Q9FV65',
 'Q71KT5',
 'KY010300',
 'Q9QZ08',
 'Q94A08',
 'Q9VG74',
 'O43286',
 'P52045',
 'UGT85A5',
 'KCE217',
 'P06987',
 'P78587',
 'P00959',
 'Q8BMJ2',
 'P28331',
 'P11509',
 'G3V8A4',
 'P77445',
 'A4WA78',
 'UGT71C3',
 'Q53GQ0',
 'Q07537',
 'P77334',
 'Q9C923',
 'P18843',
 '2a6',
 'P41888',
 'P08319',
 'KCE267',
 'P39208',
 'P52043',
 'Q9FNF2',
 'P30567',
 'Q9LSQ4',
 'P32143',
 'P38094',
 'P21599',
 'F4IUM0',
 'P02992',
 'Q0VKZ3',
 'O30847',
 'Q16739',
 'P9WMN1',
 'O86447',
 'Q93MI3',
 'O29873',
 'P41911',
 'Q8C7R4',
 'Q9KL03',
 'Q8ZL58',
 'Q4KLM6',
 'P19813',
 'P54840',
 'P75893',
 'Q3TFD2',
 'Q9HU92',
 'G5EGN2',
 'Q6PH17',
 'Q92813',
 'Q6N2K3',
 'Q9DA37',
 'Q9LYD8',
 'Q8L3B3',
 'P38169',
 'K4D422',
 'B2IZD3',
 'P41338',
 'O25001',
 'KY019260',
 'U3KRF2',
 'A0A075FBG7',
 'D2DRC5',
 'Q5B4V0',
 'O22182',
 'A0R2W4',
 'Q59327',
 'Q9VYE6',
 'Q9LW27',
 'Q9W2Q7',
 'Q12265',
 'P36148',
 'Q9VA70',
 'P0A7E5',
 'Q10132',
 'E5BDC6',
 'KC986402',
 'P94335',
 'A0A2R6Q8R5',
 'Q940S3',
 'P0C0N0',
 'O96024',
 'Q9FGX1',
 'A0A2K9RG08',
 'Q8C0N2',
 'KF831418.1',
 'Q9JM51',
 'Q7KUB1',
 'Q42545',
 'Q12055',
 'Q9UHF3',
 'Q9CW73',
 'P18064',
 'C7A2A0',
 'P94526',
 'Q00917',
 'Q10PE7',
 'Q9Z0R9',
 'Q28488',
 'P38427',
 'P40215',
 'P04764',
 'P70619',
 'Q9VG31',
 'P97564',
 'Q53W83',
 'P25722',
 'Q99J99',
 'Q38BX0',
 'Q12246',
 'P40345',
 'P31057',
 'Q06321',
 'Q08891',
 'P0A6U5',
 'F4KBT8',
 'C1FW05',
 'O87170',
 'Q5C9I9',
 'P46195',
 'F4JCU3',
 'KCE414',
 'Q15835',
 'P77596',
 'A3BMZ5',
 'Q9W423',
 'Anaerocolumna_xylanovorans',
 'Q6TAS3',
 'P9WGE9',
 'A0A076GD02',
 'UGT73C5',
 'Q94AP0',
 'Q7TVI2',
 'Q7K206',
 'Q80VA0',
 'O33342',
 'UGT84A4',
 'Q9JHC0',
 'P74653',
 'P05714',
 'Q07116',
 'P37677',
 'P0AGJ7',
 'A0A0H3JN63',
 'O54905',
 'P19099',
 'P0A744',
 'Q9VFI9',
 'A0A3T2V133',
 'P0DTE5',
 'F1QT23',
 'G1SPE9',
 'Q12305',
 'P31040',
 'P76330',
 'P0A9G6',
 'Q5GA13',
 'P9WN37',
 'Q54PV1',
 'P75960',
 'P9WKF7',
 'Q7JNK2',
 'P45470',
 'P31023',
 'A0A0Q7BW10',
 'Q9LYU4',
 'P00883',
 'P04177',
 'P42863',
 'Q66WM4',
 'O57693',
 'P29147',
 'Q8RM03',
 'Q60AP9',
 'Q9HUW7',
 'P25704',
 'C9EIP1',
 'Q99KQ4',
 'Q39760',
 'A0A193AUF6',
 'UGT89C1',
 'Q04447',
 'Q9FDS1',
 'Q42566',
 'P96884',
 'P53178',
 'Q0JF01',
 'P32378',
 'Q9M084',
 'Q06136',
 'P13569',
 'Q9VTG7',
 'P08337',
 'Q8IPJ6',
 'Q92EU5',
 'F4JYE9',
 'KCE273',
 'Q9HTB6',
 'A5KE01',
 'A8MRX5',
 'P39461',
 'P13203',
 'L0N7N1',
 'Q1LK00',
 'Q45589',
 'P26394',
 'Q46893',
 'Q9FYG0',
 'P9WQ35',
 'Q43727',
 'Q9STX5',
 'O93868',
 'P50294',
 'P11663',
 'P16861',
 'Q9HZZ1',
 'Q8IE38',
 'P15538',
 'Q4KM73',
 'O34425',
 'P23589',
 'P76215',
 'Q585M6',
 'P06935',
 'Q3UIK4',
 'P0A6L7',
 'Q8GAK7',
 'Q58297',
 'Micromonospora_avicenniae',
 'Q388T4',
 'Q9NR19',
 'Q84UV8',
 'Q9LK23',
 'Q8CF93',
 'O88455',
 'Q38802',
 'P04789',
 'Q95RR5',
 'Q4Q1I5',
 'P52029',
 'Q5JTZ9',
 'P52843',
 'Q9LCV9',
 'Q948Y1',
 'Q03SW9',
 'Q9JHD1',
 'Q99321',
 'Q03DT0',
 'P76422',
 'KCE376',
 'P04762',
 'Q5GM68',
 'P0ADX9',
 'G5ECS4',
 'F4HSX1',
 'P76469',
 'P06168',
 'P39052',
 'Q9JJH5',
 'P46645',
 'Q9ZR86',
 'P09057',
 'P53260',
 'Q59MV9',
 'SRP030024',
 'A0A1D8PR83',
 'P20477',
 'Q9LK34',
 'Q90W83',
 'O81192',
 'Q31KC7',
 'P29445',
 'P09785',
 'Actinomycetospora_chiangmaiensis',
 'UGT74F2',
 'A0A367HIX7',
 'Q4G0S4',
 'P31678',
 'O76083',
 'Q9V9T4',
 'Q5A879',
 'Q0P8Q2',
 'P49619',
 'Q83WC4',
 'I1I1F5',
 'O08560',
 'Q9LY46',
 'Q3MUY2',
 'Brevibacterium_antiquum',
 'Q9XTQ5',
 'Q7M7U5',
 'Q93ZB9',
 'Q9I2A0',
 'Q9FYL6',
 'Q7L5Y1',
 'Q9SKP6',
 'P71241',
 'Q9BU70',
 'O53361',
 'P69922',
 'P76658',
 'P61131',
 'Q50773',
 'A1XCI5',
 'P15019',
 'O43688',
 'P09233',
 'Q9C0Y4',
 'Q9ERI6',
 'A1A6H3',
 'Q1G9H4',
 'Q14642',
 'Q876R2',
 'Q09123',
 'P00572',
 'O46084',
 'P21565',
 'P05055',
 'P40970',
 'P76216',
 'Q6E7F2',
 'P11413',
 'P39722',
 'Q49610',
 'Q9UGB7',
 'Q79FX6',
 'Q57ZU1',
 'P53839',
 'O22666',
 'Q47SS3',
 'P36423',
 'P42588',
 'Q13268',
 'P39730',
 'Q9US04',
 'G5EDZ2',
 'Q89YN2',
 'P0A038',
 'O76934',
 'KCE691',
 'F4J8K0',
 'P22057',
 'A1ZA69',
 'P09601',
 'O74339',
 'P9WKE1',
 'P50336',
 'Q9VRQ1',
 'Q9HXC2',
 'KR107250',
 'P92981',
 'Q9BVG9',
 'O31503',
 'P0A6K6',
 'Q7JQ32',
 'B4FUP5',
 'P07250',
 'Q9WY08',
 'Q54RP0',
 'Q05911',
 'Q97ML3',
 'Q2GR86',
 'Q969W0',
 'P67653',
 'P29476',
 'Q96C23',
 'Q8FDQ2',
 'Q9SS43',
 'Q64685',
 'Q9ZSS6',
 'P38063',
 'P48508',
 'Q558K8',
 'Q9HYV7',
 'Q42440',
 'Q8IQA7',
 'A0PDV5',
 'Q9SUM3',
 'Q13574',
 'Q0QLF4',
 'Q9X1C0',
 'Q86SK9',
 'Q6ZMT4',
 'B2J528',
 'P28789',
 'Q9CY64',
 'A0A0K9RL25',
 'A0A1D8PNJ2',
 'Q86VZ5',
 'F8SVM6',
 'P05177',
 'P77390',
 'A0QYC2',
 'P00889',
 ...}

In [6]:
test_dataset = dataset[dataset["Substrate ID"].isin(splits[0][2])]
test_dataset

,Unnamed: 0,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,Validated,RHEA_ID,EC number,reaction_SMILES
552,609,MAAKGLLVMDVDSTLIEEEVIDLLGEKAGMGDKISEITAAAMSGEI...,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=...,0.0,Q9CHW3,compound_phospatase_dataset 160,https://doi.org/10.1073/pnas.1423570112,True,NaN,NaN,NaN
553,610,MAAKGLLVMDVDSTLIEEEVIDLLGEKAGMGDKISEITAAAMSGEI...,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=...,0.0,Q9CHW3,compound_phospatase_dataset 161,https://doi.org/10.1073/pnas.1423570112,True,NaN,NaN,NaN
554,611,MAAKGLLVMDVDSTLIEEEVIDLLGEKAGMGDKISEITAAAMSGEI...,O=c1ccn([C@@H]2O[C@H](COP(=O)(O)O)[C@@H](O)[C@...,0.0,Q9CHW3,compound_phospatase_dataset 162,https://doi.org/10.1073/pnas.1423570112,True,NaN,NaN,NaN
555,612,MAAKGLLVMDVDSTLIEEEVIDLLGEKAGMGDKISEITAAAMSGEI...,O=c1ccn([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O)[C@...,0.0,Q9CHW3,compound_phospatase_dataset 163,https://doi.org/10.1073/pnas.1423570112,True,NaN,NaN,NaN
556,613,MAAKGLLVMDVDSTLIEEEVIDLLGEKAGMGDKISEITAAAMSGEI...,O=c1ccn([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)OP(=O...,0.0,Q9CHW3,compound_phospatase_dataset 164,https://doi.org/10.1073/pnas.1423570112,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
52131,76466,MKYRAVTLESFGYQLAPVVVSTSDLEARLEPLYRQLRIAPGQLQAM...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Pelobacter_propionicus,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
52132,76467,MAFLSVNNVEIVGLAAAVPKNVETLDNLEFFAPGEAEKVMALTGIK...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Bacteroides_luti,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
52133,76468,MSAPRYSQVSAVAVRLPDEDLTTPELEELLAERNPRVDVPRGLIER...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Nonomuraea_candida,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
52134,76469,MRYQRVFINKIAYELPKEKVATSFLEEQLTDVYQELGIPLGQVEAL...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Legionella_brunensis,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
52135,76470,MTYSRIGQIAVHLPEGGRTSAEVEALVAELNPGFEPPEGLIERFTG...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Allokutzneria_albata,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN

In [8]:
results = pd.read_csv("results/test_dataset_final.csv")
results

,Test_Enzyme_ID,Test_Substrate_ID,Train_Enzyme_ID_Hit,Train_Substrate_ID_Hit,Bitscore,Tanimoto,Match_Found_in_Train
0,Q9CHW3,compound_phospatase_dataset 160,Q9CHW3,compound_phospatase_dataset 159,3.060000e-157,0.849057,1
1,Q9CHW3,compound_phospatase_dataset 161,Q9CHW3,compound_phospatase_dataset 159,3.060000e-157,0.833333,1
2,Q9CHW3,compound_phospatase_dataset 162,Q9CHW3,C18094,3.060000e-157,0.666667,0
3,Q9CHW3,compound_phospatase_dataset 163,Q9CHW3,C18094,3.060000e-157,0.736842,0
4,Q9CHW3,compound_phospatase_dataset 164,Q9CHW3,C18094,3.060000e-157,0.741379,0
...,...,...,...,...,...,...,...
6192,Pelobacter_propionicus,benzoate,Pelobacter_propionicus,TMA,0.000000e+00,0.540541,1
6193,Bacteroides_luti,benzoate,Bacteroides_luti,TMA,0.000000e+00,0.540541,1
6194,Nonomuraea_candida,benzoate,Nonomuraea_candida,TMA,0.000000e+00,0.540541,1
6195,Legionella_brunensis,benzoate,Legionella_brunensis,TMA,0.000000e+00,0.540541,1
6196,Allokutzneria_albata,benzoate,Allokutzneria_albata,TMA,0.000000e+00,0.540541,1

In [9]:
# Set the two columns as a multi-index for both DataFrames
df_reference = test_dataset.set_index(['Enzyme ID', 'Substrate ID'])
df_target = results.set_index(['Test_Enzyme_ID', 'Test_Substrate_ID'])

# Reindex df_target to match df_reference's index
df_target_reordered = df_target.reindex(df_reference.index)

# Reset index if needed
df_target_reordered = df_target_reordered.reset_index()

In [10]:
df_target_reordered

,Enzyme ID,Substrate ID,Train_Enzyme_ID_Hit,Train_Substrate_ID_Hit,Bitscore,Tanimoto,Match_Found_in_Train
0,Q9CHW3,compound_phospatase_dataset 160,Q9CHW3,compound_phospatase_dataset 159,3.060000e-157,0.849057,1.0
1,Q9CHW3,compound_phospatase_dataset 161,Q9CHW3,compound_phospatase_dataset 159,3.060000e-157,0.833333,1.0
2,Q9CHW3,compound_phospatase_dataset 162,Q9CHW3,C18094,3.060000e-157,0.666667,0.0
3,Q9CHW3,compound_phospatase_dataset 163,Q9CHW3,C18094,3.060000e-157,0.736842,0.0
4,Q9CHW3,compound_phospatase_dataset 164,Q9CHW3,C18094,3.060000e-157,0.741379,0.0
...,...,...,...,...,...,...,...
6193,Pelobacter_propionicus,benzoate,Pelobacter_propionicus,TMA,0.000000e+00,0.540541,1.0
6194,Bacteroides_luti,benzoate,Bacteroides_luti,TMA,0.000000e+00,0.540541,1.0
6195,Nonomuraea_candida,benzoate,Nonomuraea_candida,TMA,0.000000e+00,0.540541,1.0
6196,Legionella_brunensis,benzoate,Legionella_brunensis,TMA,0.000000e+00,0.540541,1.0
6197,Allokutzneria_albata,benzoate,Allokutzneria_albata,TMA,0.000000e+00,0.540541,1.0

In [11]:
df_target_reordered = df_target.reindex(df_reference.index).fillna(0).reset_index()
df_target_reordered

,Enzyme ID,Substrate ID,Train_Enzyme_ID_Hit,Train_Substrate_ID_Hit,Bitscore,Tanimoto,Match_Found_in_Train
0,Q9CHW3,compound_phospatase_dataset 160,Q9CHW3,compound_phospatase_dataset 159,3.060000e-157,0.849057,1.0
1,Q9CHW3,compound_phospatase_dataset 161,Q9CHW3,compound_phospatase_dataset 159,3.060000e-157,0.833333,1.0
2,Q9CHW3,compound_phospatase_dataset 162,Q9CHW3,C18094,3.060000e-157,0.666667,0.0
3,Q9CHW3,compound_phospatase_dataset 163,Q9CHW3,C18094,3.060000e-157,0.736842,0.0
4,Q9CHW3,compound_phospatase_dataset 164,Q9CHW3,C18094,3.060000e-157,0.741379,0.0
...,...,...,...,...,...,...,...
6193,Pelobacter_propionicus,benzoate,Pelobacter_propionicus,TMA,0.000000e+00,0.540541,1.0
6194,Bacteroides_luti,benzoate,Bacteroides_luti,TMA,0.000000e+00,0.540541,1.0
6195,Nonomuraea_candida,benzoate,Nonomuraea_candida,TMA,0.000000e+00,0.540541,1.0
6196,Legionella_brunensis,benzoate,Legionella_brunensis,TMA,0.000000e+00,0.540541,1.0
6197,Allokutzneria_albata,benzoate,Allokutzneria_albata,TMA,0.000000e+00,0.540541,1.0

In [15]:
y_true = df_reference['Binding'].values
y_pred = df_target_reordered['Match_Found_in_Train'].values

from sklearn.metrics import matthews_corrcoef, accuracy_score, precision_score, recall_score, f1_score
mcc = matthews_corrcoef(y_true, y_pred)
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)
print(f"MCC: {mcc}")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

MCC: 0.030166074952884293
Accuracy: 0.6287512100677638
Precision: 0.17374136229022705
Recall: 0.3595505617977528
F1 Score: 0.23427620632279533